### ISSUE TITLE
Encoding of Keys

### ISSUE THREAD

**Issue by axemclion** [indexeddbshim/IndexedDBShim#1]
Keys are currently not encoded properly. Numeric keys are treated like string, and hence sorting order is not maintained

**Comment by JamesMessinger** [comment]
This is fixed now.   I've added a [bunch of tests](https://github.com/axemclion/IndexedDBShim/blob/master/tests/IDBFactory/cmp-spec.js#L45) to verify that our key encoding matches native IndexedDB implementations.
