### ISSUE TITLE
PouchDB Example

### ISSUE THREAD

**Issue by ghost** [indexeddbshim/IndexedDBShim#101]
On your example page please mention that PouchDB no longer requires this shim on Android since PouchDB now uses webSQL if the database name includes the webSQL adapter in the name like this: 'websql://[my db]'.

**Comment by brettz9** [comment]
If this is still valid, would you mind submitting as a PR?

**Comment by brettz9** [comment]
If PouchDB doesn't need it, I think it is simpler to just remove the example file which I've done.
