### ISSUE TITLE
Compound queries on IDBIndex not supported.

### ISSUE THREAD

**Issue by studyro** [indexeddbshim/IndexedDBShim#105]
IDB supports create index on multiple properties and do compound query on it. The code below demonstrates it.

```
students.createIndex('males25', ['name','gender','age'], {unique:false});
```

```
var lowerBound = ['AAAAA','male',26];
var upperBound = ['ZZZZZ','male',200];
var range = IDBKeyRange.bound(lowerBound,upperBound);

var request = students.index('males25').openCursor(range,'next');
```

It seems in IDBCursor.prototype.__find method of IndexedDBShim, the SQL statement isn't correctly converted when I tried to do compound queries.

**Comment by kingIZZZY** [comment]
Duplicate of https://github.com/axemclion/IndexedDBShim/issues/117 ?

**Comment by studyro** [comment]
Exactly. 

发自我的 iPhone

**Comment by JamesMessinger** [comment]
Good news! IndexedDBShim now supports compound keys on object stores and indexes. Give it a try and let us know if you find any problems. Thanks!
