### ISSUE TITLE
Database failing to initialise or ObjectStores not being created (Android 4.2.2 and 4.1.2) using PhoneGap Build

### ISSUE THREAD

**Issue by baroquedub** [indexeddbshim/IndexedDBShim#111]
I'm trying the code example at http://blog.nparashuram.com/2012/10/indexeddb-example-on-cordova-phonegap.html

Works fine using PhoneGap Build (2.9.0) running on both a Nexus 5 and Nexus 7 (both Android 4.4.2) However on my other two devices Acer A1-810 (android 4.2.2) and Galaxy S2 (android 4.1.2) the data doesn't appear in the HTML tables. I'm unsure whether the database is failing to initialise or the ObjectStores are not being created.

I've tried updating IndexedDBShim to the latest version here on Github (v0.1.2 - 2014-01-30) but the same problem occurs. I've tried increasing the timeout before initDB() is called to 2 seconds and also, strangely, I see no error messages:

I've tried the original code in the demo:
...
}).then(function(){
 window.setTimeout(function(){
    loadFromDB("cart");
    loadFromDB("wishlist");
    downloadCatalog();
   }, 400);
}, function(){
   alert("Looks like an error occured " + JSON.stringify(arguments))
});

No error is generated and the "doing 'then' function..." alert appears (but no data is populated in the tables.

And I've tried to use promise done/fail code instead:
...
}).done(function(){
  window.setTimeout(function(){
     loadFromObjectStore("cart");
     loadFromObjectStore("wishlist");
     downloadCatalog();
   }, 400);
}).fail(function(){
   alert("failed in initDB");
}).always(function(){
   alert("always called");
});

Here, "always called" appears as expected but so does "doing 'done' function..." - no failure is reported.

Any advice on what is going wrong and how to further debug in the device would be much appreciated!

**Comment by DickvdBrink** [comment]
Are you sure it works with phonegap 2.9? Because I think you are hitting this bug (which is fixed in 3.2)
https://github.com/apache/cordova-android/commit/6e4ef508e8f9f2d396515bd1d7465481d2f1285c

Or are you using a SQLite plugin or something with phonegap 2.9? That is what I used back in the days to make it work.

**Comment by baroquedub** [comment]
Definitely using 2.9.0 - that's what I've defined in my config.xml and that's what appears on the Adobe PhoneGap Build site - in fact it's recommending that I should upgrade to 3.1.0. And yes, that demo code (and other apps I've built using the same code) all work for me but only on Android. 4.4.2.

Thanks for the tip. Following your advice and link to the bug, I've tried building using 3.3.0 but still the same, working fine on newer Nexus 5/7 but failing in the same way on older devices. :/

**Comment by JamesMessinger** [comment]
This should be fixed now.  I've [verified that it works in Android 4.2, 4.4, and 5.0](https://github.com/axemclion/IndexedDBShim/issues/178#issuecomment-93052746), but I don't have an Android 4.1 device available to test.    Please give it a try and let us know if there are any problems.  Thanks!
