### ISSUE TITLE
do not attempt to assign read-only properties

### ISSUE THREAD

**Issue by elmerbulthuis** [indexeddbshim/IndexedDBShim#113]
in strict mode, ie will not allow you to set read-only properties, so this:

window.IDBTransaction.READ_WRITE = window.IDBTransaction.READ_ONLY || "readonly";

will throw an error!

**Comment by DickvdBrink** [comment]
Thanks for the PR, hope to test it tomorrow! Thanks!

**Comment by JamesMessinger** [comment]
This has been fixed in the latest version.  All of the shimming code is wrapped in `try...catch` blocks, and we fallback to `object.defineProperty` when a property is read-only.   Please give it a try and let us know if there are any problems.  Thanks!
