### ISSUE TITLE
Bower(!)

### ISSUE THREAD

**Issue by elmerbulthuis** [indexeddbshim/IndexedDBShim#114]
Would be great if IndexedDbShim could be loaded via bower!

**Comment by jaridmargolin** [comment]
It can be loaded via bower using the following:

**SSH**

```
"dependencies": {
  "IndexedDBShim": "git@github.com:axemclion/IndexedDBShim#master",
}
```

**HTTPS**

```
"dependencies": {
  "IndexedDBShim": "https://github.com/axemclion/IndexedDBShim.git#master",
}
```

Unfortunately, this will always pull the latest from master. It would be great to have better integration. As `IndexedDBShim` is already using semver, it should be as easy as tagging the current version and pushing to Github.

```
git tag 0.1.2
git push --tags
```

**Comment by schmod** [comment]
There's now a `bower.json`, but the versions aren't being kept up to date...

**Comment by axemclion** [comment]
Should we publish to bower using travis ?

**Comment by JamesMessinger** [comment]
You can install via Bower like this:

``` bash
bower install IndexedDBShim
```

Please give it a try and let us know if there are any problems.   Thanks!
