### ISSUE TITLE
2nd param of createIndex doesn't support "sequence<DOMString>"

### ISSUE THREAD

**Issue by gitawego** [indexeddbshim/IndexedDBShim#117]
I've tried to create an index with multiple keys:

```
createIndex('channelProgrammes',['date','channel'],{unique:false});
```

but it doesn't work, i've noticed that this shim supports only simple keyPath. do you have any plan to add this support ?

see [W3C Spec](http://www.w3.org/TR/IndexedDB/#widl-IDBObjectStore-createIndex-IDBIndex-DOMString-name-DOMString-sequence-DOMString--keyPath-IDBIndexParameters-optionalParameters)

thanks a lot

**Comment by DickvdBrink** [comment]
It is definitely something we are missing in the shim which should be fixed. 
That being said, it is not something that I plan to add in the near future (just being honest here).
It might be kinda simple the implement for the IDBKeyRange.only stuff, but when using it in combination with IDBKeyRange.lowerBound I think it might be difficult to do it right.

**Comment by gitawego** [comment]
that would be cool even only for IDBKeyRange.only, 'cause I'm actually using this feature for my project, it can dramatically reduce the cursor loop times...

**Comment by kingIZZZY** [comment]
Just adding my +1 "Me too!" to this request
Not sure why I bothered posting this issue on the Microsoft Cordova plugin (which BTW doesn't seem to credit back to this project?...) https://github.com/MSOpenTech/cordova-plugin-indexedDB/issues/2

**Comment by DickvdBrink** [comment]
axemclion , the creator of this project is a Microsoft Employee working for MSOpenTech so this project wouldn't have existed without him

**Comment by axemclion** [comment]
Thanks @DickvdBrink. @kingIZZZY Sorry for being quiet on this project, have been swamped with other things. I own the other project too, but just not have had time to fix it. If we are able to fix this issue, I can update that project too :)

**Comment by kingIZZZY** [comment]
Any chance I can catch you on IRC or such so we can quickly discuss a WebSql data model / strategy for implementing this?

Thanks in advance

**Comment by axemclion** [comment]
Can we discuss it here? I think there is merit in discussing in the open. Else, we could get on IRC with the other collaborators of the project to talk about this.

**Comment by kingIZZZY** [comment]
Oh well I went ahead and hacked something up, not sure if it's any good... How does this work now, are you (axemclion or other maintainers) going to review the code to make sure it makes any sense? I'm new to GitHub and this is in fact my very first contribution/pull request ever :smile: 

Also - how do I obtain the built dist/ files from this contribution?

**Comment by JamesMessinger** [comment]
Good news!  IndexedDBShim now supports compound keys on object stores and indexes.   Give it a try and let us know if you find any problems.  Thanks!
