### ISSUE TITLE
add() does not correctly report errors on Safari

### ISSUE THREAD

**Issue by andygup** [indexeddbshim/IndexedDBShim#118]
add() incorrect reports success when there is an error. I noticed this while testing for duplicates. 

The error is correctly reported by __insertData() here https://github.com/axemclion/IndexedDBShim/blob/master/dist/IndexedDBShim.js#L1073

However, add() incorrectly reports success here https://github.com/axemclion/IndexedDBShim/blob/master/dist/IndexedDBShim.js#L1087

**Comment by mydea** [comment]
Has there been an update on this? I'm noticing this issue as well. When I try to add an existing entry via objectStore.add(...), transaction.oncomplete is called instead of transaction.onerror.

I'm having this issue when using IndexedDBShim inside of PhantomJS.

**Comment by JamesMessinger** [comment]
the `add()` method has been fixed in the latest version.   Give it a try and let us know if you find any problems.  Thanks!
