### ISSUE TITLE
transaction onerror called with no arguments safari issue

### ISSUE THREAD

**Issue by JamesKyburz** [indexeddbshim/IndexedDBShim#123]
I noticed an issue when running tests with level-js github.com/maxogden/level.js

If the user is requested to accept more space the transaction fails to commit the write.

Both

https://github.com/axemclion/IndexedDBShim/blob/master/src/IDBTransaction.js#L102
https://github.com/axemclion/IndexedDBShim/blob/master/src/IDBTransaction.js#L106

call me.onerror()

This is propagated to the node style callback with the first argument err being undefined....

Would it be possible to call me.onerror with the cause as the first argument?

**Comment by JamesKyburz** [comment]
Fixed in latest so closing.

**Comment by JamesMessinger** [comment]
:+1: Cool.  Thanks for following-up on this.
