### ISSUE TITLE
Race condition on index creation

### ISSUE THREAD

**Issue by grassick** [indexeddbshim/IndexedDBShim#127]
Creating an index is synchronous in IndexedDb but is not in the shim. This means that attempting to use the index immediately after creation may cause strange SQL errors. The readystate of `createIndex` is set but never used. Also, if multiple createIndex calls are made in a row, the behavior would be undefined.

**Comment by marianoguerra** [comment]
@grassick hi, I have the same problem, can you try this branch? https://github.com/marianoguerra/IndexedDBShim/tree/fix-race-condition-index-creation

**Comment by grassick** [comment]
I've actually moved on to write full implementations of my code for websql and Indexeddb as I had too many issues. Sorry!

**Comment by axemclion** [comment]
@grassick, @marianoguerra I have seen this issue to, have always wanted to fix it but not able to. @marianoguerra, you did send a pull request for this fix, right ?

**Comment by marianoguerra** [comment]
@axemclion here is the clean pull request https://github.com/axemclion/IndexedDBShim/pull/153

**Comment by JamesMessinger** [comment]
This issue has been fixed in the latest version.   There's no longer a race condition when creating indexes or object stores and then immediately adding data to them.
