### ISSUE TITLE
Run tests on IE10/IE11 to see compatibility

### ISSUE THREAD

**Issue by MichaelJCole** [indexeddbshim/IndexedDBShim#128]
Hi, 

I'm looking for a DB solution that is cross-browser.  IndexedDBShim sounds great!  The only problem is there is some subset of IndexedDB that is supported by Chrome/FF/Safari(w/shim)/IE.

What is that subset?  If the IndexedDBShim tests ran on IE, then I could just code to (IndexedDBShim) subtract (test failures on IE).

It's a weird request, but do you see how useful it would be for end users of your lib?

Thanks!

**Comment by JamesMessinger** [comment]
We have a [ton of new unit tests](http://nparashuram.com/IndexedDBShim/tests/index.html) that you can run against any desktop or mobile browser.   We've [verified that it works](https://github.com/axemclion/IndexedDBShim/issues/178#issuecomment-93052746) on several different browsers and devices.
