### ISSUE TITLE
add(obj) returns original object with additional 'undefined' property

### ISSUE THREAD

**Issue by cdaringe** [indexeddbshim/IndexedDBShim#132]
The value in {undefined: value} appears to be the # objects in the store.  Observed in Safari 7.0.
![screen shot 2014-05-30 at 11 09 46 pm](https://cloud.githubusercontent.com/assets/1003261/3138402/50051fe2-e88a-11e3-8cb9-1c2526b1db43.png)

**Comment by cdaringe** [comment]
Someone else had a similar issue: http://stackoverflow.com/questions/20629010/safari-shows-indexed-column-undefined-on-indexeddb-polyfill-how-to-retrieve-dat

**Comment by JamesMessinger** [comment]
This issue has been fixed.   Please give it a try with the latest version.  Thanks!
