### ISSUE TITLE
Not working on Android 4.1.2

### ISSUE THREAD

**Issue by venca163** [indexeddbshim/IndexedDBShim#137]
Hello,

I am testing IndexedDB and I came across your wonderful project for adding support to devices, which does not support it natively. Unfortunately I am not able to get callback "onsuccess" when I run index.get(). I am using Cordova and Anroid 4.1.2 device.

code example:

```
var tx = db.transaction("books", "readonly");
var store = tx.objectStore("books");        
var index = store.index("by_title");
var request = index.get("Bedrock Nights");
```

I am getting the onerror callback with error "DOMError", defined somewhere around line 1340 in IndexedDBShim.js.

(I am using code example from specification, which is running successfully on Firefox, Chrome and even on Android 4.4 emulator (as cordova android application).)

When I run tests (http://nparashuram.com/IndexedDBShim/test/index.html) on my Android browser, errors occur. Please see image with errors: http://postimg.org/image/tko3f6xgz/ .

If you have any questions, please ask. If you have any suggestions, I will appreciate it.

Thank you for looking at what is going on.

VH

**Comment by JamesMessinger** [comment]
This issue should be fixed now.   I don't have an Android 4.1.2 device available to verify, but I've verified that it now works on Android 4.2, so it _should_ work on 4.1.2 as well.   Can you please give it a try and let me know?  Thanks.

**Comment by venca163** [comment]
Hi, I've tested the same example on Android 4.1.2 today with new `indexeddbshim.js` and it's working fine. Great, thanks =).

**Comment by JamesMessinger** [comment]
:+1: Great to hear!  Thanks for testing it out
