### ISSUE TITLE
Migrations are running out of order OSX 10.9.3 Safari 7.0.4

### ISSUE THREAD

**Issue by rbriank** [indexeddbshim/IndexedDBShim#141]
When migrations are run, they aren't running sequentially.  If I add indexes for the same object in different migrations, depending on the order, later migrations overwrite earlier ones and vice versa.  I don't get the complete set of indices.

I haven't been able to figure out where the problem is happening.  I suspect an event is not being triggered correctly.

**Comment by JamesMessinger** [comment]
This issue has been fixed.   Please give it a try with the latest version.  Thanks!
