### ISSUE TITLE
IDBKeyRange upperBound ignores open flag and always excludes the end point.

### ISSUE THREAD

**Issue by poconnell7** [indexeddbshim/IndexedDBShim#154]
The fix appears to be as simple as replacing the commented out line below as shown:
    IDBKeyRange.lowerBound = function(value, open){
        return new IDBKeyRange(value, undefined, open, undefined);
    };
    //IDBKeyRange.upperBound = function(value){
    IDBKeyRange.upperBound = function (value, open) {
        return new IDBKeyRange(undefined, value, undefined, open);
    };
    IDBKeyRange.bound = function(lower, upper, lowerOpen, upperOpen){
        return new IDBKeyRange(lower, upper, lowerOpen, upperOpen);
    };
Initial testing indicates that this works, and the end point is (correctly) included by default.

**Comment by JamesMessinger** [comment]
This should be fixed now (as of version 1.0.5).  Please give it a try and let us know if you find any problems.  Thanks!
