### ISSUE TITLE
Polyfill creates websql __sysdb__ on Chrome (which has good support for IndexedDB)

### ISSUE THREAD

**Issue by matthew-andrews** [indexeddbshim/IndexedDBShim#155]
Test case here:-
http://jsbin.com/gubiwe/1
[Code http://jsbin.com/gubiwe/1/edit]

![screen shot 2014-08-09 at 12 17 52](https://cloud.githubusercontent.com/assets/825088/3865975/edee53ae-1fb7-11e4-9357-b53c0e42a0f1.png)

**Comment by JamesMessinger** [comment]
Sorry, but I don't understand what this issue is about.  Can you clarify, please?

**Comment by JamesMessinger** [comment]
This is fixed now (as of version 1.0.7).  Thanks for report it!

**Comment by JamesMessinger** [comment]
This also fixes https://github.com/axemclion/IndexedDBShim/issues/83
