### ISSUE TITLE
Filter on Index gets no result

### ISSUE THREAD

**Issue by do-web** [indexeddbshim/IndexedDBShim#172]
var singleKeyRange = IDBKeyRange.only(groupId);

```
            objStore.index('groupIndex').openCursor(singleKeyRange).onsuccess = function (event) {

                var cursor = event.target.result; };
```

The GroupIndex has multiEntry option:
objStore.createIndex('groupIndex', 'groupId', {multiEntry: true});

**Comment by JamesMessinger** [comment]
Good news!  The latest version of IndexedDBShim now supports multi-entry indexes.  Give it a try and let us know what you think.   Thanks!
