### ISSUE TITLE
When primary key value is 0 with auto increment set to false, an error is thrown: Data Error - Could not eval key from keyPath

### ISSUE THREAD

**Issue by gracezlive** [indexeddbshim/IndexedDBShim#174]
The fix is as simple as replacing the commented line with the line below. Initial testing passed.

var primaryKey = eval("value['" + props.keyPath + "']");
//if (!primaryKey) {
if (typeof primaryKey === 'undefined') {
    if (props.autoInc === "true") { getNextAutoIncKey(); }
    else { idbModules.util.throwDOMException(0, "Data Error - Could not eval key from keyPath"); }
}

**Comment by axemclion** [comment]
@gracezlive Can you please send in a pull request, I could accept it right away.

**Comment by metteo** [comment]
Issue #142 already has a fix for this.

**Comment by JamesMessinger** [comment]
I believe this is fixed now.   Please give it a try with the latest version.  Thanks!
