### ISSUE TITLE
Testing with Jest using Dexie

### ISSUE THREAD

**Issue by stevenxxiu** [indexeddbshim/indexeddbshim#18]
Issue is carried from https://github.com/dfahlander/Dexie.js/issues/647.

I'm having trouble testing `Dexie` with `Jest`, and getting the error:

```
TypeError: Illegal invocation

    at XMLHttpRequest.call (xxx/.node_modules/lib/node_modules/jest/node_modules/jsdom/lib/jsdom/living/generated/XMLHttpRequest.js:78:15)
    at XMLHttpRequest.open (xxx/node_modules/typeson-registry/polyfills/createObjectURL.js:88:33)
```

I have tried the suggestion of pegging jsdom to `16.1.0` and using this package `@indexeddbshim/indexeddbshim`, but with the same error.

The code I used for testing is:

```javascript
import Dexie from 'dexie'
import setGlobalVars from '@indexeddbshim/indexeddbshim'
import { JSDOM } from 'jsdom'
import { createObjectURL, xmlHttpRequestOverrideMimeType} from 'typeson-registry/polyfills/createObjectURL-cjs.js'

test('test', async () => {
  const { window } = new JSDOM('',  {
    url: 'https://example.com/',
  })
  setGlobalVars(window)
  global.XMLHttpRequest = window.XMLHttpRequest

  URL.createObjectURL = createObjectURL
  XMLHttpRequest.prototype.overrideMimeType = xmlHttpRequestOverrideMimeType()

  const db = new Dexie('recordings', {indexedDB: window.shimIndexedDB, IDBKeyRange: window.IDBKeyRange})
  db.version(1).stores({files: 'name'})
  const table = db.files
  const blob = new window.Blob([new Uint8Array([1, 2, 3])])
  await table.put({name: 'file.bin', data: blob})
})
```

**Comment by brettz9** [comment]
You pegged to the exact version, not adding a `^` or `~` before the version, I presume, right?

If so, could you please prepare a minimal test repo which I can clone?

It is getting late for me here but can hopefully look into this tomorrow.

**Comment by stevenxxiu** [comment]
Sure I setup a repo at https://github.com/stevenxxiu/jest_dexie_test. And yes that's what I did.

**Comment by brettz9** [comment]
As per https://github.com/stevenxxiu/jest_dexie_test/pull/1 , you need to update `@indexeddbshim/indexeddbshim` (to avoid late-loading the XHR polyfill) and define `Blob` globally. And there is no need to peg jsdom at a lower version. It works with the current latest version 16.2.2.

Closing as that should resolve, but feel free to comment further as needed.

**Comment by stevenxxiu** [comment]
Thanks a lot! That fixed my local test as well. I would have no idea how to fix this myself.

I would be totally stuck without you here. You deserve a 🏆!

(I additionally needed `global.FileReader = window.FileReader` in my local tests).

**Comment by brettz9** [comment]
Well, you made things pleasant by following the feedback, preparing the test repo, etc. And I know this kind of thing would not have been fun to debug without already knowing the internals.

There are really some trade-offs in using browser APIs as the default and requiring Node users to tweak their environments. Thankfully there is jsdom and Node has increasingly added some browser APIs (like `URL` and `URLSearchParams`), but I know it's a bit different for normal Node apps in having to set globals.
