### ISSUE TITLE
Race Condition caused by __addToTransactionQueue

### ISSUE THREAD

**Issue by kberryman** [indexeddbshim/IndexedDBShim#180]
If you are adding sql statements to a queue out side of the actually transaction this causes a race condition.  The WebSQL transaction automatically closes once it does not have any other statements execute.  This functionality is described here: http://dev.w3.org/html5/webdatabase/#executing-sql-statements in statement 1.  It says 

> 1. If the method was not invoked during the execution of a SQLTransactionCallback, SQLStatementCallback, or SQLStatementErrorCallback then raise an INVALID_STATE_ERR exception. (Calls from inside a SQLTransactionErrorCallback thus raise an exception. The SQLTransactionErrorCallback handler is only called once a transaction has failed, and no SQL statements can be added to a failed transaction.)

Since the __addToTransactionQueue is determining when to run each statement you can't pass the same SQLTransaction through to every call back.  It is likely the transaction will close at some point then you will see Dom Exception 11 InvalidStateError.

I am seeing this issue when I attempt to do a series of data base upgrades in row on Safari 7.1.4  Something like upgrading from database version 0 to database version 8.  There is no way to hold a WebSQL transaction open manual so the only thing I can think of would be to remove the statements from executing on the same transaction or to by pass the queueing process. Is there a reason that statements are getting queued vs just executed directly on the transaction and allowing the database to queue them as it sees fit?

**Comment by JamesMessinger** [comment]
Can you provide some sample code to illustrate the issue?  I want to make sure I understand the exact problem.   Are you using the latest code?  We've been making **lots** of changes and bug-fixes lately, and we have [unit tests for back-to-back database upgrades](https://github.com/axemclion/IndexedDBShim/blob/master/tests/IDBFactory/open-spec.js#L191).

**Comment by kberryman** [comment]
@BigstickCarpet I forked the repo ( https://github.com/kberryman/IndexedDBShim/tree/testSafariMultiUpgrades ) and added a test to the test/index.html file.  I also had to modified the test index file to check for Safari 7.14 by user agent and use the shim.  If you run with the tests under the "FailingTest" tag the multiple updates test will fail with a Dom Exception 11: Invalid State.  I also included what I think may be the best fix for the issue.  If you pull the tag "passingTest"  you can see the changes and the tests will pass.

**Comment by JamesMessinger** [comment]
Ok, should be fixed now.  Get the latest version and give it a try.
