### ISSUE TITLE
Does not work in IE 11 - Compatibility Mode 9

### ISSUE THREAD

**Issue by jeanpaulnet** [indexeddbshim/IndexedDBShim#181]
Test (http://nparashuram.com/IndexedDBShim/test/index.html) is failing in IE 9 (in compatibility mode >  F12 > Choose mode).

IE 9 does not have IndexedDb, but only WebSQL! The shim is supposed to switch back to WebSQL and support offline database.  But it is throwing error.

**Comment by JamesMessinger** [comment]
Unless I'm mistaken IE has never supported WebSQL (see [caniuse.com](http://caniuse.com/#search=websql)).   You can verify this yourself using `console.log(typeof window.openDatabase)`.   In any version of IE, this statement returns `undefined`.   In browsers that support WebSQL, this statement returns `function`.

**Comment by axemclion** [comment]
@BigstickCarpet  I can confirm that IE did not support WebSQL - I was a PM doing some initial IndexedDB work for IE.

**Comment by jeanpaulnet** [comment]
Thanks.
