### ISSUE TITLE
Problem upgrading from older version of the shim

### ISSUE THREAD

**Issue by kingsfleet** [indexeddbshim/IndexedDBShim#201]
I am upgrading from a version of the shim from last year with existing data stores and it fails to start because of the line in IndexDBObjectStore that tries to parse keyPath:

```
    this.keyPath = JSON.parse(storeProperties.keyPath);
```

In my existing stores keyPath is a simple string value, rather than the quoted string this would appear to require. Is there any documentation on the change in format? I am running inside a Cordova app so I have a load of data to upgrade.

**Comment by kingsfleet** [comment]
The previous version of the Shim appears to come from around 26th September 2014 if that helps.

**Comment by JamesMessinger** [comment]
Hi.  Sorry for the delayed response.  I've been on vacation.

We're using [semantic versioning](http://semver.org/), so changes to the major version number are considered breaking and not backward compatible.  Specifically, whenever we make changes to the underlying database schema, we bump the major version number.   So the `0.x` database schema is not compatible with the `1.x` schema or the `2.x` schema.

Unfortunately, there's no automatic data migration.  You'll have to delete and re-create your database if you want to upgrade to a new major version of IndexedDBShim.   The other alternative is to only upgrade to the latest _minor_ version that matches your current _major_ version.  So, if you're currently using IndexedDBShim `1.0.2`, then you could upgrade all the way to `1.0.15` without any problems.

**Comment by kingsfleet** [comment]
Ah no problem, I am using a version from September 2014 so I guess this is before version 1.x and therefore won’t be compatible with the 1.x series. Still not to worry, it is shame to loose this historic data; but all private so won’t matter.

Would it be worth updating the readme for Cordova, and similar, users to make clear the versioning policy? Cheers and thanks for all your hard work.
