### ISSUE TITLE
Filtered count for paging not possible

### ISSUE THREAD

**Issue by emertechie** [indexeddbshim/IndexedDBShim#202]
I need to implement paging over filtered data so I have code that fetches a page of data as well as the total count. Something like:

``` js
var index = listingsStore.index("theIndexName");

// 1. Filtered cursor for page (uses "cursor.advance(offset)" elsewhere to fetch page of data)
var pageCursor = index.openCursor(queryRange, indexDirection);

// 2. Filter count request for correct totalCount
var totalCountRequest = index.count(queryRange);
```

That all works fine with native IndexedDB but when I use the shim I get "DataError: Not a valid key" when calling `index.count(queryRange)`.

The issue seems to be that the `IDBIndex.prototype.count` function doesn't support accepting a range even though the [spec says it should](http://www.w3.org/TR/IndexedDB/#widl-IDBIndex-count-IDBRequest-any-key).

I'm willing to take a stab at a pull request for this as I really need it. Implementation suggestions welcome.

Thanks for the awesome library

**Comment by alekseykulikov** [comment]
+1.
I'm also missing support of `IDBKeyRange` in `IDBIndex.prototype.count`.
Temporary hack is to use `index.openCursor()` instead of `index.count()` when range is provided.

**Comment by brettz9** [comment]
Support for ranges to `IDBIndex.count()` (as well as to `IDBObjectStore.get`) are now in `master`. Thanks for the report!
