### ISSUE TITLE
add support for direction="prevunique" when filter by index

### ISSUE THREAD

**Issue by alekseykulikov** [indexeddbshim/IndexedDBShim#204]
I think solution should be similar to https://github.com/axemclion/IndexedDBShim/blob/master/src/IDBCursor.js#L239 but work not only for multiEntry indexes.

P.S.
Thanks a lot for pushing this library on new level!

**Comment by brettz9** [comment]
This support is now added in `master`. Note that there are still some w3c tests related to cursors (when used with readwrite operations) which are not passing as mentioned in #257 .
