### ISSUE TITLE
Transaction error should propagate to db.onerror callback

### ISSUE THREAD

**Issue by alekseykulikov** [indexeddbshim/IndexedDBShim#205]
You already call onerror callback on transaction. So solution might be to add:

``` js
idbModules.util.callback("onerror", me.db, evt);
```

to https://github.com/axemclion/IndexedDBShim/blob/master/src/IDBTransaction.js#L109

**Comment by unkillbob** [comment]
I think this is causing issues for us whereby when Safari prompts the user to permit access to more disk space the current transaction that triggered the prompt silently fails. This results in data being lost without our code being any the wiser.

**Comment by JamesMessinger** [comment]
This is fixed now (as of v2.2.1)
