### ISSUE TITLE
IDBObjectStore.opencursor with null keyrange

### ISSUE THREAD

**Issue by DickvdBrink** [indexeddbshim/IndexedDBShim#207]
https://developer.mozilla.org/en-US/docs/Web/API/IDBIndex/openCursor

> If the key range is not specified or is null, then the range includes all the records

Currently this is an error, I have a fix ready for this but I need to create a test case for this too.
Creating an issue for it so I don't forget :)

The error is `Not a valid key`

**Comment by JamesMessinger** [comment]
Hmmm... sounds like this should be caught by one [these](https://github.com/axemclion/IndexedDBShim/blob/28cf794b8a3c097f94497c1ea341dca4cfe81acb/tests/IDBIndex/openCursor-spec.js#L395) [two](https://github.com/axemclion/IndexedDBShim/blob/28cf794b8a3c097f94497c1ea341dca4cfe81acb/tests/IDBIndex/openCursor-spec.js#L442) tests.   Can you look at them and see what's up?  Notice that there is some variance in behavior between browsers (hence the `env.browser.isIE` and `env.browser.isSafari` checks), so maybe that has something to do with it.

**Comment by DickvdBrink** [comment]
@BigstickCarpet, ah thanks for the two pointers. The test do test `undefined` but they don't test for `null` and because https://github.com/axemclion/IndexedDBShim/blob/master/src/IDBCursor.js#L15 of this line a IDBKeyRange is created with null which isn't allowed (there is also some additional code later which also checks for `undefined`)
