### ISSUE TITLE
SQLite index on index columns?

### ISSUE THREAD

**Issue by rkistner** [indexeddbshim/IndexedDBShim#210]
This is more of an implementation question, not a bug.

This project has a very interesting implementation for IDB indexes on top of SQLite.

I see indexes are created by creating a new BLOB column in the table, and using a specific encoding to allow correct sorting/filtering.

This is done here:

https://github.com/axemclion/IndexedDBShim/blob/master/src/IDBIndex.js#L96

However, I don't see that a SQLite index is ever created on that column. It seems like the entire point of the special encoding of keys would be allowing a SQLite index to be used on that. Am I just missing it? Or is there a reason that no index is added?

**Comment by brettz9** [comment]
I think we'd be open to a PR for this, as I don't see why we shouldn't have a SQLite index on the column (and possibly others) unless there is potential for file size problems or lack of implementation support for indexes (I don't know).

I think we should probably add indexes optionally via config.

**Comment by brettz9** [comment]
This is now implemented in `master`/RC 8. When the config `useSQLiteIndexes` is set to `true`, we apply simple indexes for the following:

1. The table we use to manage database name/versions (`dbVersions`)
2. The table we use to keep track of store metadata (`__sys__`)
3. The `key` column of the store content table (a table named after the store)
4. The index columns of the store content table (a table named after the store)

Btw, the reason for the special encoding of keys also relates to IndexedDB sorting requirements.

Thanks for the report!
