### ISSUE TITLE
Remove use of eval() to allow this to be used with Content Security Policy

### ISSUE THREAD

**Issue by jrzerr** [indexeddbshim/IndexedDBShim#211]
I create Chrome Apps using AngularJS and I am also using [Google's wrapper around Cordova](https://developer.chrome.com/apps/chrome_apps_on_mobile) to allow Chrome Apps to run on iOS and Android.  This library has been the link to get IndexedDB working on iOS.

However, the use of eval within this library prevents me from using on iOS without modifications because using eval violates the [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/Security/CSP) which is required to be followed for a Chrome app.  In particular, using AngularJS, I have to run in special [ngCsp mode](https://docs.angularjs.org/api/ng/directive/ngCsp).

I first encountered the use of eval in the [Key getValue function here](https://github.com/axemclion/IndexedDBShim/blob/master/src/Key.js#L334).  For that particular case, the eval is unnecessary.  Line can be changed from:

``` javascript
return eval("source." + keyPath);
```

to:

``` javascript
return source[keyPath];
```

at least for my use case.  Could maybe use some additional error checking...

I wanted to start this as a bigger issue that might be able to be used for ongoing progress should removing eval from the library be something that others like me are looking for.

**Comment by JamesMessinger** [comment]
Yeah, I 100% agree with you that we can and should get rid of the `eval()` statement.  And, as you pointed out, it's not even very difficult to do.  Just a matter of getting around to it.  :)

The solution is a little bit more complicated than your example, since keyPaths can be deep (e.g. `person.name.last`) or compound (e.g. `["person.name.first", "person.name.last"]`).  But it's still totally doable.

**Comment by xlc** [comment]
[`_.get`](https://lodash.com/docs#get) can be handy for this https://www.npmjs.com/package/lodash.get

**Comment by brettz9** [comment]
@xlc: Thanks, I've been working on a branch on my fork which does it pretty cleanly, but still some more work to do. Btw, `eval()` is also used in `Sca.js`. Are there any volunteers to make an eval-free version there (the apparent original author of that file, @jkleinsc , are you free?)?

**Comment by brettz9** [comment]
I've pushed the fork which eliminates `eval` in `Key.js` to `master`, but still have the `Sca.js` to deal with.

**Comment by brettz9** [comment]
Since `Sca.js` is the one left (and although I recently discovered `cyclonejs` which appears handy for object-to-object cloning), this should be considered in connection with #267 .

**Comment by brettz9** [comment]
This has now been fixed in `master`. `eval` is no longer used, whether for keys or cloning (courtesy of typeson/typeson-registry).
