### ISSUE TITLE
Default value for `open` argument in IDBKeyRange.lowerBound and IDBKeyRange.upperBound is `false`

### ISSUE THREAD

**Issue by alekseykulikov** [indexeddbshim/IndexedDBShim#212]
It's mentioned in [W3C spec](http://www.w3.org/TR/IndexedDB/#range-concept) and [IDBKeyRange test specs](https://github.com/w3c/web-platform-tests/blob/master/IndexedDB/idbkeyrange.htm#L30).

The fix should add `|| false` to current code:

``` js
IDBKeyRange.lowerBound = function(value, open){
        return new IDBKeyRange(value, undefined, open || false, undefined);
};
IDBKeyRange.upperBound = function(value, open){
        return new IDBKeyRange(undefined, value, undefined, open || false);
};
```

I can provide pull requests if needed.

**Comment by brettz9** [comment]
Greetings Aleksey!

Maybe this was a problem earlier, but currently, if the `lowerOpen` or `upperOpen` parameters are falsey, the current behavior is to turn them into `false` ([handled in the constructor](https://github.com/axemclion/IndexedDBShim/blob/master/src/IDBKeyRange.js#L21-L22)).

FYI, we're currently passing adapted versions of the `IDBKeyRange` portions of your W3C and indexedDBmock tests. Still a ways to go, but coming along...

Will close for now, but feel free to comment, etc.

**Comment by alekseykulikov** [comment]
Thank you Brett for starting to work on this library!
I will submit a few more issues :)
