### ISSUE TITLE
Multiple object store in safari

### ISSUE THREAD

**Issue by rrNuvoPoint** [indexeddbshim/IndexedDBShim#213]
Hello,

I am using your fine plugin. However. Creating more than two object stores is not possible. I will get an error from indexeddb. Seems to be because safari is actually using indexeddb and not websql. A workaround is just to create multiple databases with one object store. But that seems very wrong to me..

**Comment by rrNuvoPoint** [comment]
i had to check if navigator is chrome. If not to manually force for websql. That worked :+1:

**Comment by JamesMessinger** [comment]
Please see the [Known Issues](https://github.com/axemclion/IndexedDBShim#known-issues) notes.  There's a [bug in Safari](https://bugs.webkit.org/show_bug.cgi?id=137034) that prevents us from being able to replace `window.indexedDB`.  There are a couple workarounds for this in the Known Issues notes.

**Comment by rrNuvoPoint** [comment]
Oh sry. I thought i marked this as resolved. But yes. Thank you.
