### ISSUE TITLE
indexeddbshim + dexie + safari issue

### ISSUE THREAD

**Issue by isaacbdawson** [indexeddbshim/IndexedDBShim#214]
So I am using the latest dexie and indexeddbshim with safari and it appears indexeddbshim is creating websql databases instead of indexeddb, but to my understanding that should be ok?

The tables do get created (I can see them in web inspector).

However on the dexie add I get "undefined is not an object (evaluating 'types[getType(key)].encode') followed by "[object SQLError]".

I am unclear as to whether this is a dexie issue or an indexeddbshim issue.

**Comment by isaacbdawson** [comment]
Figured it out.
Happens when an indexed field is null.

**Comment by JamesMessinger** [comment]
:+1:   Glad you figured it out.  It's always best to isolate code to just one library to determine where the problem is.

**Comment by isaacbdawson** [comment]
Just an FYI, this should not happen and is indicative of some kind of issue in the shim.
The work around is to just not let your indexed fields be null, but it should not be necessary.

**Comment by JamesMessinger** [comment]
Hmmm... I would need to see a code sample to understand exactly what you mean.  We have [several](https://github.com/axemclion/IndexedDBShim/blob/4b653ee73ed48a9c654390a33838d0895988695f/tests/IDBObjectStore/add-put-spec.js#L310-L320) [tests](https://github.com/axemclion/IndexedDBShim/blob/4b653ee73ed48a9c654390a33838d0895988695f/tests/IDBFactory/cmp-spec.js#L259-L271) for all sorts of key values (null, undefined, NaN, empty arrays, empty objects, etc.), and we've done our best to be fully compliant with [the spec](http://www.w3.org/TR/IndexedDB/#key-construct) while also accounting for certain [non-standard behaviors in some browsers](https://github.com/axemclion/IndexedDBShim/blob/4b653ee73ed48a9c654390a33838d0895988695f/tests/IDBFactory/cmp-spec.js#L273).

**Comment by isaacbdawson** [comment]
If you view this page with Safari:
http://www.dementedplayground.com/Dexie.js-master/samples/ajax-populate/populateFromAjaxCall_with_shim.html

Use the web inspector and you should be able to see what I am referring to.

**Comment by JamesMessinger** [comment]
Awesome!  Thanks for putting together that demo.  It's definitely a bug in the shim.  We'll need to check the spec to see how it _should_ behave, and then write a test to repro the problem.

I've created a [new issue](https://github.com/axemclion/IndexedDBShim/issues/215) for this.

**Comment by apankov** [comment]
Hello,
I had experienced the same error when was using Dexie.js together with their addons Observable and Syncable. I had success in debugging the root of the problem and seems I found solution that is working for me just fine. Idea is that Dexie.js is defining their own wrapper around collection record, that wrapper contains additional info about datatypes of record fields (useful for code auto-completion). For instance here the example (shortened):

``` javascript
            var SyncNode = Dexie.defineClass({
                //id: Number,
                myRevision: Number,
                type: String, // "local" or "remote"
                lastHeartBeat: Number,
                deleteTimeStamp: Number,
                url: String,
                isMaster: Number,
                ...
            });
```

And here is typical usage:

``` javascript
            mySyncNode = new SyncNode({
                myRevision: latestRevision,
                type: "local",
                lastHeartBeat: Date.now(),
                deleteTimeStamp: 0,
                isMaster: 0
            });
            db._syncNodes.add(mySyncNode).then(function() { ... });
```

When this record is getting saved, object `mySyncNode` does not contain field `url` directly, but as far as I understand correctly it's prototype contains (please excuse me if I'm wrong). So `Key.getValue` does `eval("source.url")` and returns value `String`, which is then gets interpreted by `getType()` as "object" (not as "null" as was mentioned above).

I have patched IndexeddbShim library, as I said it solved my problems. However I understand my implementation is hackish so I'm not doing pull request. But I believe that may share you light of what's going on. Here is the patch https://github.com/12devs/IndexedDBShim/commit/1a53288d111cad5889aeb30696936534716cc456 . Also I have created simple demo for your convenience, you can see how app is failing with "original" indexeddbshim and works fine with "patched" -- http://dexie-demo.my-new-site.com/index.html

**Comment by dpogue** [comment]
@apankov We've been using your patch for a while, but things broke recently when we added an object store with a compound index. I believe your patch will never try to populate that index because the compound key isn't a property of the value.

Currently investigating https://github.com/axemclion/IndexedDBShim/pull/231 as a possible alternative.

**Comment by apankov** [comment]
@dpogue Indeed, my patch doesn't take care of such case.
