### ISSUE TITLE
Why did you drop the MIT license option?

### ISSUE THREAD

**Issue by brody2consult** [indexeddbshim/IndexedDBShim#218]
First, I would like to thank you guys for your work to develop, publish, and maintain this project. I appreciate that you added dual-licensing MIT/Apache 2.0 a couple of years ago. I have been maintaining the Cordova sqlite plugin project and am planning to integrate your IndexedDB shim. The MIT license was quietly removed on April 15. Did you do this on purpose?

**Comment by axemclion** [comment]
@brodybits The last commit on LICENSE seems to say dual license on Apache + MIT, so it may have been a mistake. 

Btw, love your Cordova storage plugin :)

**Comment by brody2consult** [comment]
Thanks! Please let me know when you get this restored. And thanks for your complement on my Cordova sqlite plugin, it has taken quite a bit of work to keep it maintained.

**Comment by brettz9** [comment]
I've added back the MIT license in `master` (removed apparently by accident with ecf8ee4f6d5ce6b5cc5036f9a39ae3f6c028dfa6 ). Thanks for the report!

Btw, a whole lot of changes--I didn't see how the Cordova file was to be tested--welcome to add a PR to clarify/update to make sure it is working (I just tweaked a bit of the various HTML files styling to be more conventional).
