### ISSUE TITLE
IndexedDBShim does not work in webworkers

### ISSUE THREAD

**Issue by PedroJusto** [indexeddbshim/IndexedDBShim#219]
Hi! despite of there is a workaround, your library is not prepared to be used in WebWorkers .

**Comment by JamesMessinger** [comment]
Can you post a code sample?  Maybe on [JSFiddle](https://jsfiddle.net/) or [Plunker](http://plnkr.co/)?

**Comment by PedroJusto** [comment]
the problem is that webworker does not have access to window object. my workaround is to define in webworker : 

var window = self;
and import indexeddbshim.js with importScripts("indexeddbshim.js"); inside webworker

**Comment by brettz9** [comment]
I've pushed some changes to `master` which should address the problem. Would someone mind testing and ideally offering a PR containing a test (and any further fixes)? Thanks!

**Comment by brettz9** [comment]
And in case you already tried pulling, sorry, I realized I hadn't pushed the changes to this repo's `master`. Now available.

**Comment by brettz9** [comment]
This should be fixed in `master`. I'm closing but feel free to reopen.

**Comment by axemclion** [comment]
@brettz9 Just wanted to drop in and say thanks for the awesome work you are doing with the IndexedDBShim - I can see that it is helping a lot of people. :)

**Comment by brettz9** [comment]
Thank you, @axemclion . Not sure if it is helping anyone yet, but it is encouraging to know there is eagerness for the release. Am feeling a bit better these days and on my agenda to try to get ready (as I am able) for a 3.0.0 release as per https://github.com/axemclion/IndexedDBShim/issues/262#issuecomment-254413002 . Very grateful for being able to build on such a strong foundation!
