### ISSUE TITLE
IndexedDB not working on IOS devices

### ISSUE THREAD

**Issue by saroj990** [indexeddbshim/IndexedDBShim#220]
Hi All,
I am using indexedDB(angular indexedDB) in my application .it is running fine everywhere except IOS devices .I am using indexedDBShim.js for IOS which should use the WebSql if indexedDB is not supported.But i am getting errors.
Can anybody help me to get out of the problem?

**Comment by DickvdBrink** [comment]
Can you explain what errors you are having?

**Comment by ndevtag** [comment]
Have the same Problem on IOS, using shim with the jQuery Plugin. 
Getting an "AbortError", when try to use the put function on objectstore is created on the fly, when not exists:

``` js
var putPromise = db.objectStore(segmentname, true).put(JSON.stringify(jsonObject), key);
```

This calls the fail handler giving an "AbortError".

OS: IOS 9
TestCases indexeddb.shim.js runs successfull
TestCases jquery.indexeddb.js some
Someone any idea?

![img_0594 1](https://cloud.githubusercontent.com/assets/14348688/9962440/01f1953e-5e26-11e5-8517-3e0d0a074a27.PNG)

![img_0592 1](https://cloud.githubusercontent.com/assets/14348688/9962347/9a9befe2-5e25-11e5-9e03-9afb1349fb79.PNG)

![img_0593 1](https://cloud.githubusercontent.com/assets/14348688/9962355/a4267d84-5e25-11e5-9084-fdbe049be729.PNG)

**Comment by saroj990** [comment]
I left using indexedDB for IOS devices its buggy in behavior . finally i used WebSQL for IOS and IndexedDB implementation for other devices.

**Comment by ndevtag** [comment]
The shim uses WebSQL for indexedDB implementation. Unfortunately i have not the choice to left it. I have to get working this shim in IOS.

**Comment by JamesMessinger** [comment]
Try running [these tests instead](http://nparashuram.com/IndexedDBShim/tests/index.html?useShim=true).   It'll help us pin-down exactly what errors you're seeing

**Comment by saroj990** [comment]
I have tested this on IPad but still no luck. it breaks i means stop somewhere in between and doesn't go further.

**Comment by saroj990** [comment]
Does this shim work for you , just curious to know

**Comment by DickvdBrink** [comment]
Hmz,, failing for me on iOS 7.1 on the IDBFactory.deleteDatabase Test

> should return an IDBOpenDBRequest
> `undefined` is not an object (evaluating 'db.close') (deleteDatabase-spec.js)

I'm currently unable to debug this but it looks like there is something wrong..

**Comment by ndevtag** [comment]
The shim do not work for me, but i have to get it work.

**Comment by JamesMessinger** [comment]
I don't have iOS 7.1 to test on, but I've tested on iOS 8 and iOS 9, and [all of the tests](http://nparashuram.com/IndexedDBShim/tests/index.html?useShim=true) pass, including [the `deleteDatabase` tests](http://nparashuram.com/IndexedDBShim/tests/index.html?useShim=true&grep=IDBFactory.deleteDatabase).

@saroj990 and @ntagdev - It would be helpful if you could post some sample code that reproduces the error.  Also, please make sure you read the [known issues on iOS](https://github.com/axemclion/IndexedDBShim#ios) and use one of the two workarounds listed there.

**Comment by ndevtag** [comment]
Ok, i've found the problem. The app did not use the shim in ios Safari, because window,indexedDb ist defined.

**Comment by saroj990** [comment]
I don't know i may be wrong but i have tried this and got no luck.I wish i am wrong and it works for you.

**Comment by brettz9** [comment]
@ntagdev or @saroj990 : have you manually called `shimIndexedDB.__useShim();` in your code?

**Comment by brettz9** [comment]
There appears to be a problem with iOS9 and IndexedDB for non-Safari browsers. Our new code (discussed in #252) forces iOS9 non-Safari browsers to use the shim despite them supposedly having IndexedDB support. 

Until our next release, you can change your project's bower dependency line for "IndexedDBShim" to https://github.com/axemclion/IndexedDBShim#ios9 and run `bower install` in your project directory.

Closing for now but feel free to comment further or reopen if your issue is not resolved.

**Comment by brettz9** [comment]
Apologies, it seems like there is nevertheless an issue with Safari too on iOS9?

**Comment by corse-xx** [comment]
is there a full fix for this at all or even at ETA? I have currently reverted all the way back to v0.1.2 from 2014-09-22 and its working in that...but there have obvs been a few improvements since then :p

**Comment by brettz9** [comment]
Sorry, no ETA. PRs welcome.

**Comment by corse-xx** [comment]
doh, ok i will go back through the versions to see where it got broken (sorry id take a look at fixing it permanently but am mid project!) and post here if i see anything obvious.

**Comment by corse-xx** [comment]
ok i'm not sure what i missed but under phonegap serve i can have this working and not working easily...
1. downloaded the 2.2.1 repo and copied indexeddbshim.min.js into my app - Work FINE in ios9
2. downloaded the master repo and copied indexeddbshim.min.js into my app - broken immediately

The file size differences in the min files are immense (46kb to 230kb), did i miss something here?

**Comment by brettz9** [comment]
If you are looking for the latest working version for ios9, it'd be fine to go back and see where it got broken, but if you are willing to debug and get all of the benefits of the many bug fixes, I would just start with the latest in `master` and see where we can fix it for ios9.

As far as `master` being broken for ios9, yes, that is known. I would just try digging around in the code and checking console and see what turns up.

As far as file size, the new code is being transformed by `babel`. Looking at the non-minified code, a large amount of that code is taken up by `babel-polyfill` which I have imported to allow us to use some other ES6 convenience features. If the import statement in `setGlobalVars.js` is removed, the grunt processes might avoid including that polyfill file, but you will need to provide polyfills for the likes of `Object.assign` to avoid the current code breaking.

**Comment by brettz9** [comment]
In https://github.com/axemclion/IndexedDBShim/issues/252#issuecomment-228707973 , there were reports that things were working in iOS9 (though there have been further changes since then).

Welcome to try the 3.0.0-rc.3 version out for a spin. Closing as this should be fixed. Feel free to reopen if you find anything to the contrary.

**Comment by ImoyaCas** [comment]
Hi! i have a problem with a indexeddb query on IOS devices:
$.indexedDB(dbName).objectStore(tablename).index("INDICE").each(function(itemLocal) {
       itemLocal.delete();
}, [VALORINDICE]).then(function() {
                    callback();
                }, function() {
                    console.log("error");
                });
The problem is if there is more than one record that matches the index, it does not eliminate them, it eliminates the first one and leaves. But if for example I put console.log (itemLocal) instead of itemLocal.delete() if it shows all those that match the index. 
Any suggestions for something I can do?

**Comment by brettz9** [comment]
What version of indexedDB and configuration are you using?

**Comment by ImoyaCas** [comment]
I use a Jquery Plugin for the IndexedDB API (Jquery-IndexedDB) but the version of indexeddb i don´t know, where can i see that?

**Comment by brettz9** [comment]
For questions about IndexedDB itself, ask somewhere like StackOverflow (or for the plugin, contact the plugin owner). This is for reporting issues with IndexedDBShim, a library to let you use IndexedDB on some older browsers (though most recent changes have been oriented toward Node support rather than all older browsers).

**Comment by ImoyaCas** [comment]
first ask me what version I use, And then you tell me that? 
if it's not the place to ask this, tell me first

**Comment by ImoyaCas** [comment]
the header is "IndexedDB not working on IOS devices" and this is just what happens to me

**Comment by brettz9** [comment]
Your extra post helped me notice you repeated "indexeddb" instead of "indexeddbshim"... Sheesh...

**Comment by ImoyaCas** [comment]
... Sheesh...???  the title is "IndexedDB not working on IOS devices" not "Indexeddbshim not working on IOS devices" change the title and avoid mistakes. thank you.

**Comment by brettz9** [comment]
I didn't write the heading dude, and I wasn't blaming you for asking the question--I am getting annoyed though with you blaming me for criticizing that I didn't discover your mistake right away. This is the IndexedDBShim site, by the way...

**Comment by axemclion** [comment]
I request that we acknowledge the good work that @brettz9 is doing with maintaining the project.

**Comment by DickvdBrink** [comment]
Agreed, Good job @brettz9 and thanks for all the hard work!

**Comment by JamesMessinger** [comment]
Hear! Hear! Maintaining an open source project can seem like thankless work sometimes, but we appreciate all you do, @brettz9.  Keep it up

**Comment by brettz9** [comment]
Thanks a lot, fellas! Thanks for all your good work and reports as well as kind encouragement...

Btw, I expect all of the past contributors to the project ought to enjoy hearing from other folks here who are using the software about how they are putting it to use (and whether you're using 3.*)...

Or if it is for private purposes, just the fact that you're using it...
