### ISSUE TITLE
Does IndexedDBShim have a TypeScript Definition file?

### ISSUE THREAD

**Issue by hope4555** [indexeddbshim/IndexedDBShim#221]
Does IndexedDBShim has a TypeScript Definition file?
So we could easily use it in TypeScript?

**Comment by axemclion** [comment]
We wrote [one for WebSQL](https://github.com/borisyankov/DefinitelyTyped/blob/master/cordova/plugins/WebSQL.d.ts), but i have not seen any for IndexedDB yet. 

Would be a good contribution to have.

**Comment by hope4555** [comment]
Thank you
When using IndexedDBShim in typescript i guess we need a single Definition file and not one for WebSQL and other for IndexedDB. Am i correct?

**Comment by axemclion** [comment]
That is correct, you just need a typescript file for IndexedDB. The typescript definition is not specific for the shim as the shim is supposed to expose IndexedDB API anyway. If we have a definition file for IndexedDB, that would be good.

**Comment by steven-ayogo** [comment]
Dexie has typescript, so we use that. works with indeseddbshim

**Comment by brettz9** [comment]
@steven-ayogo : But I don't see Dexie having TypeScript definitions for the full IndexedDB API, no?

**Comment by brettz9** [comment]
It does have types as of 13.0.0 .
