### ISSUE TITLE
IDBTransaction missing methods inherited from EventTarget (also missing on IDBDatabase, IDBTransaction, IDBRequest, IDBOpenDBRequest)

### ISSUE THREAD

**Issue by CraigCav** [indexeddbshim/IndexedDBShim#229]
According to MDN,  [IDBTransaction ](https://developer.mozilla.org/en-US/docs/Web/API/IDBTransaction) inherits from [EventTarget](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget), however, the IndexedDBShim implementation of IDBTransaction does not provide `addEventListener`, `removeEventListener` or `dispatchEvent` methods, and instead only provides event handlers for `oncomplete`, `onerror` and `onabort`.

Related to: https://github.com/axemclion/IndexedDBShim/issues/32

**Comment by brettz9** [comment]
`master` is now supporting those methods. Note, however, that bubbling has not yet been implemented properly, nor the ability for `preventDefault` to have an effect--although support for both is now possible within the [underlying EventTarget library](https://github.com/brettz9/eventdispatcher.js/tree/early-late-listeners) once I may find the time to utilize within IndexedDBShim. You may wish to track #253 now as this particular feature is implemented (with the caveats above), though feel free to comment further.
