### ISSUE TITLE
getAll implementation is missing

### ISSUE THREAD

**Issue by nirgit** [indexeddbshim/IndexedDBShim#232]
Great job first of all.

Second, I did want to use the API getAll to retrieve all the "records" kept in the store, but saw
that it wasn't implemented. Any chance of seeing this soon?

Thanks a lot & keep up the good work

**Comment by brettz9** [comment]
Support has been added in `master` (along with the other missing APIs `IDBObjectStore.getAllKeys`, `IDBObjectStore.getKey`, `IDBIndex.getAll/getAllKeys`, `IDBCursor.continuePrimaryKey`).

However, I have not added any new tests for these, hoping as I may be able to, to get the full set of current W3C tests working again (and fully so). Feel free to open new issues with any particular bugs encountered.

Thanks for the report!
