### ISSUE TITLE
Type "object" undefined

### ISSUE THREAD

**Issue by wibimaster** [indexeddbshim/IndexedDBShim#239]
The object "types" does not know the "object" type ; test on a iPhone 4S with iOS 8.3, got a big fail with undefined object.

I do a PR to fix that, can you tell me if it's OK for you ?
#238

Thanks !

**Comment by brettz9** [comment]
As mentioned in #238, this is now fixed in `master`. Thanks for the report and PR!

**Comment by brettz9** [comment]
Sorry, I was premature in adding my code. Please pull again from `master` if you've already updated, as I've fixed things to either throw a proper error or silently ignore, as per spec behavior. Please see my comment at https://github.com/axemclion/IndexedDBShim/issues/215#issuecomment-227218203 .
