### ISSUE TITLE
DB Open fails on Firefox >= 43.x and Dexie.org lib

### ISSUE THREAD

**Issue by ilDon** [indexeddbshim/IndexedDBShim#240]
I use DexieJS (dexie.org) to handle all Indexeddb activities (db open / queries / etc.) and I've noticed that there might be a bug when using IndexedDBDShim.

On Chorme, Safari, and Opera, everything works as expected on WebSQL, but then on Firefox I get the following error:

`Error: Database not open. Following error in populate, ready or upgrade function made Dexie.open() fail: TypeError: window.openDatabase is not a function`

As of now, I have solved it wrapping thew whole code of IndexedDBShim inside a condition:

``` js
if(navigator.userAgent.indexOf('irefox') < 0){
    // IndexedDBShim library
}
```

However this doesn't seem as the best solution ever. I believe that there must be some issue in the way the polyfill is triggered.

**Comment by brettz9** [comment]
A number of changes are present now in `master`. I'm not sure how they will affect your issue, but if you wouldn't mind trying it and reporting back, it'd be appreciated.

**Comment by ilDon** [comment]
Sorry for the late reply, I ended up not using IndexedDBShim with firefox, but I'll do some testing asap to give you a feedback on this :-)

**Comment by brettz9** [comment]
We have a new release candidate (currently no. 3) available for testing. Dexie also now gives new advice on use with our shim. This should be fixed, so closing, but feel free to reopen if you encounter issues.
