### ISSUE TITLE
Shim uses WebSql on latest Chrome version (Chrome 50) - instead of IndexedDb

### ISSUE THREAD

**Issue by ChristianWeyer** [indexeddbshim/IndexedDBShim#242]
Using the official example here http://nparashuram.com/IndexedDBShim/tests/index.html?useShim=true we get a lot of databases created in WebSql and not in IndexedDb with latest Chrome version.

![image](https://cloud.githubusercontent.com/assets/888718/14633288/3bdfc942-061d-11e6-8754-3c4515045229.png)

This is obviously not the expected behavior ;)

Any idea what could be wrong?
Thanks!

**Comment by brettz9** [comment]
With URL structured to include `/tests/index.html?useShim=true`, that argument is what causes Chrome to use its WebSQL capabilities. You can remove that "useShim" arg from the URL or click the "Switch to Native IndexedDB" button. I think this should address your issue, but feel free to reopen or comment further if I've missed something.
