### ISSUE TITLE
Problem with running individual tests

### ISSUE THREAD

**Issue by brettz9** [indexeddbshim/IndexedDBShim#248]
When running the QUnit testing in the browser, if one opts to "Rerun" a particular test, some of these tests do not work properly due to the manner in which the tests were added. It would be nice to work around this issue.

Mocha has this problem as well insofar as running individual tests does not seem to delete the old ones first.

**Comment by axemclion** [comment]
@brettz9 I am not able to spend time actively maintaining the project. Given the PRs you have sent to the project, would you be interested in contributing to the project as a committer ?

**Comment by brettz9** [comment]
Sure

**Comment by axemclion** [comment]
@brettz9 You are now a collaborator, and should be able to merge in your PRs. I would also appreciate if you can look at some other recent PRs too ... thanks for helping out.

**Comment by brettz9** [comment]
My pleasure, thanks a lot!

**Comment by brettz9** [comment]
Oh, and do you want me to ping you when an issue or PR needs closing, etc.?

**Comment by axemclion** [comment]
@brettz9 I will try to look at the activity, but you should feel free to do what is best for the community ...

**Comment by brettz9** [comment]
The QUnit aspect is no longer relevant as I've moved those tests to Mocha. I'm tracking the remaining mocha issue on the new package at https://github.com/indexeddbshim/indexeddbshim/issues/10
