### ISSUE TITLE
ShimEvent doesn't have `preventDefault` method

### ISSUE THREAD

**Issue by xlc** [indexeddbshim/IndexedDBShim#253]
I am using IndexedDBShim and [sklad](https://github.com/1999/sklad) and got this error on iPad running iOS 8 & 9:

> Error: TypeError: evt.preventDefault is not a function. (In 'evt.preventDefault()', 'evt.preventDefault' is undefined)

In [this function](https://github.com/1999/sklad/blob/e6595c286f9898bace95b463b39b231fe0044250/lib/sklad.js#L913): 

```
openConnRequest.onerror = function (evt) {
        if (isResolvedOrRejected) {
            return;
        }

        evt.preventDefault();
        reject(ensureError(evt.target.error));

        isResolvedOrRejected = true;
    };
```

[ShimEvent](https://github.com/axemclion/IndexedDBShim/blob/c09d66479a0f63c415437e9d4f815347b45f1888/src/Event.js#L25) should have `preventDefault` method and other methods on `Event` object.

**Comment by brettz9** [comment]
This also interconnects with #229 and #241

**Comment by brettz9** [comment]
FYI, I've added support for `addEventListener` and other EventTarget features via my fork of [eventdispatcher.js](https://github.com/brettz9/eventdispatcher.js) and although the fork supports `preventDefault` (as with bubbling), I haven't yet taken advantage of it within IndexedDBShim, so calling it on the code in `master` will not throw but will currently have no effect. I intend to implement though, so can let you know when it may be ready.

**Comment by brettz9** [comment]
This is now supported in `master`.  Looking to finish the following though until ready for a release: https://github.com/axemclion/IndexedDBShim/issues/262#issuecomment-254413002

**Comment by brettz9** [comment]
Actually, I neglected to notice you were asking about preventing within an open request--the `versionchange`/`upgradeneeded` (and when ready, `blocked` and `closed`) ought to support all of `EventTarget`, but currently that is not ready or reviewed, so I will reopen, but the normal request->transaction->connection->window.onerror support has been added.

**Comment by brettz9** [comment]
The `AbortError` error firing on `IDBOpenDBRequest` requests (which aborted or were closed) is now done in `master`. There are some tangential matters which are not complete (e.g., upgradeneeded reversions), but the bubbling work is complete.

Note that your `preventDefault` should now have no effect (as per point 3.2.1 of [this section](http://w3c.github.io/IndexedDB/#dom-idbfactory-open) of the spec).

**Comment by brettz9** [comment]
FWIW, the ugpradeneeded reversions are applied where possible (esp. in Node where we can prolong a transaction).
