### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by bennycode** [indexeddbshim/IndexedDBShim#255]
Today I wanted to use `IndexedDBShim` in a node application. According to your readme I wrote this piece of code:

```javascript
const setGlobalVars = require('indexeddbshim');
var Dexie = require('dexie');
GLOBAL.window = GLOBAL;
setGlobalVars();

var db = new Dexie('MyDatabase');

db.version(1).stores({
  friends: 'name, age'
});

db.open();
```

But I am always receiving `ReferenceError: window is not defined`. Can you tell me what I am doing wrong?

**Comment by brettz9** [comment]
Node support is not yet part of a published release. Please see my comment at https://github.com/axemclion/IndexedDBShim/issues/254#issuecomment-228575304  .

**Comment by brettz9** [comment]
Although we still don't have a regular versioned release, you should be able to load in npm via:

```json
 "dependencies": {
    "indexeddbshim": "https://github.com/axemclion/IndexedDBShim"
  },
```

See https://github.com/axemclion/IndexedDBShim/issues/254#issuecomment-281909340
