### ISSUE TITLE
Cursor caching

### ISSUE THREAD

**Issue by brettz9** [indexeddbshim/IndexedDBShim#257]
Hi @axemclion ,

With the caching of cursor data, a problem comes into play when the data becomes stale, not as a result of internal methods, but when say the store object is used to delete an item.

While we technically could track state between these classes, for example, having the `IDBObjectStore.delete` method get cursor iteration over the cache to ignore the deleted item, I'm afraid this may be prone to very difficult code maintenance.

Do you want to lose the performance benefits of caching in favor of easier maintenance or disregard the code maintenance troubles and try to update any active cache.

A middle ground might be invalidating the cursor cache whenever a method such as `IDBObjectStore.delete` runs.

**Comment by DickvdBrink** [comment]
I believe the caching was giving us a very big performance boost in cases with significant rows. 
Maybe we should consider only using a cache on "read" transactions and not using a cache on "readwrite"?

**Comment by brettz9** [comment]
The problem doesn't occur though if one only uses read operations (regardless of whether readonly or readwrite). I can see about invalidating the cursor cache when a write operation is called (and probably adjusting the offset or such).

**Comment by brettz9** [comment]
Actually, I now doubt whether invalidating the cache could work because when say deleting an item, we wouldn't know, for example, whether the deleted item had already been iterated or not, so we wouldn't know whether to adjust the offset or not, not to mention the need for reconstituting `advance` offsets. I am thinking that the only options are to either get rid of the cache or to track the state ourselves, though as mentioned, the latter would probably get a bit ugly, even if it may be the better option. There should also be need to address the concern that changes in the cache only be made after the database had been updated by the write operation so that, for example, if an "add" operation fails, the user would not have iterated the item.

**Comment by brettz9** [comment]
This issue should now be fixed in `master`. Note the breaking change (in case you were relying on these pseudo-private properties).
- Breaking change: As moved away from SQL offsets for `IDBCursor` retrieval,
  remove `__lastKeyContinued` property (we can use `__key`); also remove
  unused `__multiEntryOffset`
- Fix: For `IDBCursor`, move from SQL offsets to utilization of last key as
  per spec (and as needed for discovering any db modifications)
- Fix: In conjunction with `IDBCursor` `continue` and `advance` caching,
  trigger cache resets/changes (for `IDBCursor`: `delete`, `update`
  and for `IDBObjectStore`: `add`, `put`, `delete`, `clear`);
