### ISSUE TITLE
intel xdk installation

### ISSUE THREAD

**Issue by daniele777** [indexeddbshim/IndexedDBShim#258]
Hi i ask support i try to add IndexedDBShim
 in intel xdk to get compatible indexdb in ios 9... i get this error
![shim error](https://cloud.githubusercontent.com/assets/8341788/17278594/f175a22e-5760-11e6-969c-94394cb20045.PNG)

help!

**Comment by brettz9** [comment]
Sorry, not familiar with the SDK you are working with. iOS9 was reported as being fixed fairly recently, so you might give our latest RC a try. If you are still having problems, you might need to report the issue to your SDK or give us some more concrete information.
