### ISSUE TITLE
iOS 9 WKWebView support

### ISSUE THREAD

**Issue by xlc** [indexeddbshim/IndexedDBShim#270]
WebSQL is not supported by WKWebView in iOS 9: https://bugs.webkit.org/show_bug.cgi?id=137760
But IndexedDBShim force to use WebSQL on iOS 9.
Is anyway to make it patch native IndexedDB instead of using WebSQL?

**Comment by brettz9** [comment]
That is what `src/polyfill.js` is for (and the file's use within `src/setGlobalVars.js`). However, I could really use help testing that (once my version 3.0.0 changes are ready) as I have been making many changes which are fixing a number of issues on Chrome and Node but I haven't done any real checking with iOS.

**Comment by brettz9** [comment]
And as a result, I haven't really been applying improvements made within the shimming code to the (more limited) polyfill code.

**Comment by brettz9** [comment]
We've abandoned support for `polyfill.js` which patched bad IndexedDB implementations.

However, if you are just talking about avoiding our code forcing WebSQL, I've added an option, `avoidAutoShim` to `master` to do this. Closing as should settle the issue but feel free to reopen if not. Should be added to a new release candidate soon.

**Comment by brettz9** [comment]
Now added to 3.0.0-rc.4
