### ISSUE TITLE
Database open fails with Opera and Linq2IndexedDB

### ISSUE THREAD

**Issue by marcoreni** [indexeddbshim/IndexedDBShim#28]
I tried to use this shim to enable my web application in Opera and Firefox (the app works fine in Chrome).

I received a strange error in Opera, so I decided to run the tests on http://users.telenet.be/kristofdegrave/test/ (which integrate the Shim).

I received this errors on my console (and I don't get any result):

Uncaught exception: TypeError: Cannot convert 'e.target' to object

Error thrown at line 3178, column 4 in <anonymous function: request.onerror>(e) in http://users.telenet.be/kristofdegrave/Scripts/Linq2IndexedDB.js:
    pw.error(e.target, [e.target.errorCode, e]);
called via Function.prototype.apply() from line 27, column 3 in callback(fn, context, argArray, func) in http://users.telenet.be/kristofdegrave/Scripts/indexeddb.shim.js:
    (typeof context[fn] === "function") && context[fn].apply(context, argArray);
called from line 1026, column 5 in dbError(msg) in http://users.telenet.be/kristofdegrave/Scripts/indexeddb.shim.js:
    idbModules.util.callback("onerror", req, [e]);
called from line 1043, column 7 in <anonymous function: deleteDatabase>(tx, data) in http://users.telenet.be/kristofdegrave/Scripts/indexeddb.shim.js:
    dbError("Database does not exist");
Uncaught exception: TypeError: Cannot convert 'e.target' to object

Error thrown at line 3178, column 4 in <anonymous function: request.onerror>(e) in http://users.telenet.be/kristofdegrave/Scripts/Linq2IndexedDB.js:
    pw.error(e.target, [e.target.errorCode, e]);
called via Function.prototype.apply() from line 27, column 3 in callback(fn, context, argArray, func) in http://users.telenet.be/kristofdegrave/Scripts/indexeddb.shim.js:
    (typeof context[fn] === "function") && context[fn].apply(context, argArray);
called from line 1026, column 5 in dbError(msg) in http://users.telenet.be/kristofdegrave/Scripts/indexeddb.shim.js:
    idbModules.util.callback("onerror", req, [e]);

Running the page in Firefox 17beta results in some tests to fail, but my application runs fine.

What can cause this problem?

**Comment by axemclion** [comment]
Are you able to run the polyfill without a library - http://axemclion.github.com/IndexedDBShim/test ? Do you see any errors with that on Opera?

**Comment by marcoreni** [comment]
The test on that page runs correctly, no errors are reported.

**Comment by axemclion** [comment]
This could be an issue with the way LINQ is written. Can you isolate this to a single function to take a look at what is going on ?

**Comment by marcoreni** [comment]
I made some tests in the Opera console.

Trying to open/create the database works fine.

Then I try to select some object from the database (at the time of the call the database is created but still empty, but on Chrome this is not a problem and the function goes straight to the "done" callback) but I get an error (and none of the debugging lines is printed out). These are the functions I'm using. 

``` javascript
ObjectStoreName = "MyStore"
var dbConfig = new Object();
dbConfig.version = 1;
dbConfig.definition= [{ 
    version: 1,
    objectStores: [{ name: ObjectStoreName, objectStoreOptions: { autoIncrement: true, keyPath: "id" } }],
    indexes: [{ objectStoreName: ObjectStoreName, propertyName: "category", indexOptions: { unique: false, multirow: false } }]
}];

db = window.linq2indexedDB("MyDatabase", dbConfig);

---

//id_category gets set before the function is called
db.linq.from(ObjectStoreName).where("category").equals(id_category).select(["id","title","url"]).then(function (args) {
    console.log("done");
}, handleError, function(args) {
    console.log("progress");
}); 
```

I tried enabling debug-mode to be able to give you some more info but I received a `TypeError: Cannot convert 'window.console.warning' to object` and I still haven't figured out why.

**Comment by kristofdegrave** [comment]
Hey,

I'm the one working on the linq2indexeddb lib. I'm aware of the issue and I am currently working on it. The problem is that in the oncomplete the shim doesn't pass any arguments. I have a workaround and will push it asap.

greetings

Kristof

**Comment by axemclion** [comment]
Do you think it should be fixed in the shim instead of the library ?

**Comment by kristofdegrave** [comment]
Well I have a work around added in my framework, but it would be best to fix it in the shim too so it works like the specs. What is now present in the context should be accesible in the target property of the argument.

**Comment by kristofdegrave** [comment]
@LinoLinux The 1.0.21 version of the linq2indexeddb library solves this issue.

**Comment by brettz9** [comment]
It looks like an event is now being passed always to `oncomplete` along with a `target`. Closing then, but feel free to report any problems.
