### ISSUE TITLE
It should be possible to choose the directory to save database files (Node)

### ISSUE THREAD

**Issue by erikvold** [indexeddbshim/IndexedDBShim#297]
When using this repo with NodeJS it would be nice to be able to select where on the system the database files are stored, at the moment I'm guessing that `process.cwd()` is used.

**Comment by brettz9** [comment]
As a temporary workaround, you could override `CFG.win`'s `openDatabase`, though you'd have to turn off the new on-by-default `CFG.deleteDatabaseFiles` until the fix. But shouldn't be too hard to support.

**Comment by brettz9** [comment]
Fixed in `master`. Note, however, that I accidentally pushed a commit prior to that commit which was incomplete and intend to fix shortly. There is a regression with `CFG.cacheDatabaseInstances` when not `false`.

**Comment by brettz9** [comment]
The regression is now also fixed in `master`.
