### ISSUE TITLE
Not a valid key

### ISSUE THREAD

**Issue by bboydflo** [indexeddbshim/IndexedDBShim#306]
I have setup a test page for the indexeddb functionality I need in my app and currently only testing on Android 4.1.2 WebView to make sure that the IndexedDBShim + latest Dexie works.

The shim is only loaded when needed (!Modernizr.indexedb || iosVersion <9 ) before Dexie.

With the latest IndexedDBShim (3.0.1) I cannot get these tests to pass, not even the first one which is opening a database connection. I keep getting "DOM Exception 18" and if I test something else the app hangs because I do not get any response or error back. 

I have then tried to use latest Dexie + an older version of IndexedDBShim (2.1.1) and I almost all the tests to pass besides deleting a row by id. There I get a Dexie error: "Not a valid key" (see first comment). In this setup the same "SECURITY_ERR: DOM Exception 18" is caught by the IndexedDBShim. 

I have made some research and this error can be related with opening an WebSQL database from 'file:///' but I have the correct setup, because it has worked before (Dexie 1.5.7 + IndexedDBShim 2.1.1). 

To resume: I cannot get latest Dexie (v2.0.0-beta.11) to work with IndexedDBShim 2.1.1 and I cannot figure out what the problem is. 

Any help is highly appreciated.

**Comment by brettz9** [comment]
Are you trying to open a prior existing database? If so, that won't work with 3.* version which is definitely breaking...

I would try stepping through the code in the non-minified dist file and see where things get tripped up.

**Comment by bboydflo** [comment]
Wow! Thank you very much! I've got this working. There was already a database created using a IndexedDBShim 2.1.1 and that was the issue.

**Comment by brettz9** [comment]
Great to hear... Will close then, but feel free to report back on anything else...
