### ISSUE TITLE
Failure to create window.indexedDB running in node if initialConfig is supplied

### ISSUE THREAD

**Issue by jimsugg** [indexeddbshim/IndexedDBShim#307]
Node 7.8.0
IndexedDBShim 3.0.1

If I run the following code in node, window.indexedDB is undefined:

`const setGlobalVars = require('indexeddbshim');
global.window = global;
setGlobalVars({checkOrigin: false});
if (!window.indexedDB) {
  console.log('No indexedDB!');
} else {
  console.log(window.indexedDB);
}`

However, the following code works:

`const setGlobalVars = require('indexeddbshim');
global.window = global;
setGlobalVars();
if (!window.indexedDB) {
  console.log('No indexedDB!');
} else {
  console.log(window.indexedDB);
}`

However, the second code example is not useful because I cannot open a database with an opaque origin.

I am trying to use this to unit test some IndexedDB code in node.

Update: from reading CHANGES.md, I see that a workaround is to add this statement:
window.location = {origin: 'https://some.com'};

However, initialConfig setting is still broken in this case - I would rather just set checkOrigin.

**Comment by brettz9** [comment]
Please note the signature of `setGlobalVars`:

    setGlobalVars(<winObj or null>, initialConfig)

You need to pass in `null` for the first argument (or `window`) (and your `initialConfig` object as the second argument).

That should address the issue, so will close, but feel free to comment further.

**Comment by jimsugg** [comment]
Oof. 🤦‍♂️  Of course that works. Thanks.
