### ISSUE TITLE
IDBShim v3.0.1 doesn't work

### ISSUE THREAD

**Issue by ulshv** [indexeddbshim/IndexedDBShim#309]
I get `Uncaught ReferenceError: regeneratorRuntime is not defined` when using IDBShim v3.0.1 in any browser (desktop or mobile). Line 23 in `src/DOMStringList.js`

**Comment by brettz9** [comment]
Have you added `<script src="node_modules/babel-polyfill/dist/polyfill.min.js"></script>`?

That is a recently-added requirement.

Also, FYI, 3.0.2 was just released today (though it is not related to this issue).

**Comment by ulshv** [comment]
@brettz9 just added polyfill, it didn't help. I use latest desktop Chrome but I still get this error. So there is no IDB shim on iOS now. Previous versions (2.x) worked perfectly fine.
Here's not working example with IDBShim 3.0.2 - https://jsfiddle.net/xf2zrL4p/110/, and working with v2.2.1 - https://jsfiddle.net/xf2zrL4p/111/.

**Comment by ulshv** [comment]
I really don't know what happend but I don't get this error now, even on iPhone 4s (iOS 5.1), tested on browserstack. Any ideas? I was getting this error for last 2 days (since I decided to try v3.0.1).

**Comment by ulshv** [comment]
Anyways, I will let you know if I will get `regeneratorRuntime is not defined` error again. It seems everything works fine now.

**Comment by brettz9** [comment]
I saw that `regeneratorRuntime` error myself at some point and also saw it disappear (I think maybe in Node too). If you see it recur (with the polyfill on), we could look at removing our use of generator functions, but it is more elegant if we can keep them.

**Comment by ulshv** [comment]
I started getting this `regeneratorRuntime` errors again...
Example: https://jsfiddle.net/xf2zrL4p/117/

**Comment by ulshv** [comment]
Sorry, I forgot to include babel-polyfill... =/ 
Everything ok!
