### ISSUE TITLE
Cannot supply flags when constructing one RegExp from another.

### ISSUE THREAD

**Issue by mbrevda** [indexeddbshim/IndexedDBShim#311]
When duplicating regexes on some older browsers, flags cannot be added (testing Safari 6 atm, due to embedded device constraints). My particular error is being thrown on

```js
new RegExp(expandsOnNFD, 'g')
```
[in which case](https://github.com/axemclion/IndexedDBShim/blob/be2c7e6619129d2e705b255cacda1c346fec491d/src/util.js#L62) `expandsOnNFD` is already a regex, which is being duplicated.

Here is a test case: http://jsbin.com/nidevotuqi
Im currently including the code from [here](https://unpkg.com/indexeddbshim@3.0.4/dist/indexeddbshim.js)

**Comment by brettz9** [comment]
Could you try replacing

```js
new RegExp(expandsOnNFD, 'g')
```

with

```js
new RegExp(expandsOnNFD.source, 'g')
```
?

I guess the copying of regex objects is an ES6 feature that Babel is not yet polyfilling.

If the fix above works, it'd be helpful to know whether there are any other issues in such older browsers (ideally tested against our various browser tests) as it'd be nicer to keep with the more succinct syntax if it's not going to be possible to support older browsers anyways (though of course, if we can support, that would be ideal).

**Comment by mbrevda** [comment]
I can confirm that on this Safari 6 esqueue browser, adding `.source` prevents the error.

**Comment by brettz9** [comment]
Sorry been busy--this should be addressed by https://github.com/babel/babel/issues/5978 for which I hope to get to a PR, though probably not at least for a week or so.

**Comment by mbrevda** [comment]
I think I mentioned that we didn't go with indexeddbshim in the end, so I'm
not holding my breath. Thanks for the update thought!

**Comment by brettz9** [comment]
Sorry but when you were testing it, do you recall whether you were including the babel polyfill file or only the indexeddbshim file?

**Comment by mbrevda** [comment]
I think I tired with the polyfill, but don't recall

**Comment by brettz9** [comment]
Going to close this unless someone else can confirm the babel polyfill doesn't solve it...

**Comment by StabbarN** [comment]
Babel polyfill using Babel 7 with babel-preset-env useBuiltIns set to 'entry' doesn't work. It results in "Cannot supply flags when constructing one RegExp from another"

Docs about useBuiltIns: https://new.babeljs.io/docs/en/babel-preset-env.html#usebuiltins

I made an example here https://github.com/StabbarN/indexeddbshim-regexp

- Example not working: https://github.com/StabbarN/indexeddbshim-regexp
- Example where it works by setting useBuiltIns to false and adding `'@babel/polyfill'` to webpack entry,  see https://github.com/StabbarN/indexeddbshim-regexp first commit, that is https://github.com/StabbarN/indexeddbshim-regexp/commit/3821b2959bb1ad920021fc1ee370c6c443efe29c

It seems like Babel's preset-env strips some regexp polyfill.

**Comment by brettz9** [comment]
It'd be great if you could take a look at https://github.com/babel/babel/issues/5978 or at least report your test case there... I'm pretty limited atm to investigate more closely...

**Comment by brettz9** [comment]
Thank you very much for building that test case and reporting this to Babel, @StabbarN (and @mbrevda for the original issue). Glad we can use more elegant code as well as solve things at the root, but if it takes too long, let me know and we can just add the longer way...

**Comment by brettz9** [comment]
In publishing 3.6.0 just now, I went ahead and stomached the 7 extra characters to make it work for everybody. :-) I made a note to revert once Babel may apply a fix.

**Comment by StabbarN** [comment]
No release yet but this PR seems to fix it https://github.com/babel/babel/pull/7809
