### ISSUE TITLE
Browsers that don't support WebSQL

### ISSUE THREAD

**Issue by habahut** [indexeddbshim/IndexedDBShim#333]
I am trying to port a web app that uses IndexedDB in a JavaFX application. JavaFX supports neither WebSQL or IndexedDB, but the webapp I am using requires IndexedDB. Do you have any suggestions for how to make this work?

Thanks,
Trevor

**Comment by brettz9** [comment]
It appears you or someone has filed on https://stackoverflow.com/questions/53952910/indexeddb-for-javafx-webview-with-no-websql-support so closing that it may be more suitably handled there.
