### ISSUE TITLE
Repository settings

### ISSUE THREAD

**Issue by brettz9** [indexeddbshim/IndexedDBShim#353]
@axemclion , I'd really appreciate your help here, as I'm really eager to:

1. Set up the `master` branch for use on Github Pages, so we can offer a stable site for the demos. (githack.com does seem to be up now, but IIRC, it wasn't working for a time).
2. I'd like to be able to set up an option for people to sponsor our work through Github Sponsors. This can take a lot of time to maintain, and it'd be nice to have an opportunity to get a little support.

For either of these, I'd need repository settings access. I really don't want to make a fork, as I think it is convenient for continuing users not to need to switch packages, but if necessary, I think that is the route I will need to go if I still won't hear back from you. I also can't seem to find a personal email for you, not helped out by the fact that VPN access here in China is restricted, so therefore Google access is also limited here.

Thanks for all your work in getting this project going as well as in your demos and blogs that made IndexedDB usage easier for all!

**Comment by brettz9** [comment]
Not having heard back, and given your previous encouragement to start a new repo, I've released now at https://github.com/indexeddbshim/indexeddbshim/issues so closing here.

**Comment by axemclion** [comment]
Sorry for not responding. Please go ahead.

**Comment by axemclion** [comment]
Also, if you think we should move this repo to an organization of its own, so that you have more control, that would be cool too.

**Comment by brettz9** [comment]
I think archiving as you suggested in https://github.com/axemclion/IndexedDBShim/issues/249#issuecomment-628222827 would be a very good idea, though maybe first making a new patch release which we mark as deprecated (by `npm deprecate` with its message pointing to the new package URL) so that those checking for updates can get informed that the package is deprecated (I don't know if marking an old package as deprecated is enough to cause npm to show the message when the user updates other dependencies).

I've already got you a part of the organization per https://github.com/indexeddbshim . Let me know if you have any access issues if you decide to resume work, and thank you again so much for all the pioneeering work you did not only the core code, but in the massive number of tests and very helpful demos/blog posts you have produced.

**Comment by axemclion** [comment]
Sounds good. Let me know if you have done npm deprecate, and i can then archive this repo. Thanks for all your work.

**Comment by brettz9** [comment]
On further reflection, @axemclion ... To minimize the impact on existing users (and since adoption for `@indexeddbshim/indexeddbshim` is still rather low), what do you think of our instead:

1. Transferring ownership of the repository to https://github.com/indexeddbshim/  (I may need to first delete https://github.com/indexeddbshim/indexeddbshim , though it could be tried). I assume that will make proper redirects on the Github side. There is an option within project Settings to make such transfers of ownership, apparently just requiring that you have commit access in the targeted organization--which I've assigned.
2. Continue using `indexeddbshim` for npm, with my just using the current contents of `@indexeddbshim/indexeddbshim` as a new version for `indexeddbshim`. I can then deprecate my newer npm package `@indexeddbshim/indexeddbshim` in favor of `indexeddbshim` (while still allowing for the `@indexeddbshim` scope to be used if there is ever a need for other subprojects related to indexeddbshim).

**Comment by axemclion** [comment]
@brettz9  - let me know when to do the transfer.

**Comment by brettz9** [comment]
I think you can go ahead and try to transfer.

**Comment by axemclion** [comment]
Looks like `https://github.com/indexeddbshim/indexeddbshim` already exists. Should I delete it before transferring? I cannot delete it since I am not an admin.

**Comment by brettz9** [comment]
I've set you up as a co-owner (sorry, should have done that earlier). Unless there is another way to make a redirect, I think you can go ahead and delete it first before transferring. I can then push my commits since that time and then deprecate the npm package I created back in favor of `indexeddbshim`.

**Comment by axemclion** [comment]
The repo is now transferred to [https://github.com/indexeddbshim/indexeddbshim](https://github.com/indexeddbshim/indexeddbshim).

I have also renamed the forked repo in the org to [https://github.com/indexeddbshim/indexeddbshim-forked](https://github.com/indexeddbshim/indexeddbshim-forked)

**Comment by brettz9** [comment]
Excellent, thanks so much for persisting with this, and my apologies for a somewhat slow response time (have not been feeling too well, and maybe will even need to curb my contributions, but figured it was still good to go ahead with this and have an organization umbrella). I've now:

1. Pushed all of the changes from `@indexeddbshim/indexeddbshim`over to this repo.
2. Released 6.6.0 with those changes (and a few other updates)
3. Publishing `master` on Github Pages: https://indexeddbshim.github.io/IndexedDBShim

Needless to say, please feel free to add yourself to [`.github/FUNDING.yml`](https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository#about-funding-files) to have the opportunity to receive any sponsorships.
