### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by nuevoalex** [indexeddbshim/IndexedDBShim#354]
In IDBDatabase.js an array is kept which stores all transactions:

https://github.com/axemclion/IndexedDBShim/blob/7a2bd336cc0f60245ec308b25b112d857315c90a/src/IDBDatabase.js#L36

This array never has elements removed and will grow indefinitely as an application runs resulting in out of control memory growth.

**Comment by brettz9** [comment]
Thank you for the report. Please note that while I am maintaining the issues here for now, all further work I plan to do (including accepting of PRs) is on https://github.com/indexeddbshim/indexeddbshim .

**Comment by brettz9** [comment]
Released as part of 15.0.1 . Thanks for the report!
