### ISSUE TITLE
Attempt to iterate a cursor that doesn't exist

### ISSUE THREAD

**Issue by nbrustein** [indexeddbshim/IndexedDBShim#368]
Rarely, when trying to write to the database in the wild, we see a `Attempt to iterate a cursor that doesn't exist` error in our error reporting services.

I found [this issue](https://github.com/pouchdb/pouchdb/issues/8329) that sounded kind of similar. But that issue seemed to only be happening to people when the app was backgrounded. In our case it's happening when someone is actively using the app.

Do you have any idea what could lead to an error like this? 

I haven't tried just building in a retry for this error, but maybe that's worth it?

I'm using [Dexie](https://dexie.org/), [cordova-sqlite-storage](https://github.com/storesafe/cordova-sqlite-storage) and setting things like this:

```
const shim = {};
setGlobalVars(shim, { win: window.sqlitePlugin /* DEBUG: true */ });

dexieConfig.indexedDB = shim.indexedDB;
dexieConfig.IDBKeyRange = shim.IDBKeyRange;

**Comment by brettz9** [comment]
I'm afraid that without a means to replicate (and with the message being a browser one), I hesitate to label this a definitive bug. Closing for now, but can reopen if obtain further details. Thanks!
