### ISSUE TITLE
Not compatible with projects using @babel/runtime > 7.18.0

### ISSUE THREAD

**Issue by colbymelvin** [indexeddbshim/IndexedDBShim#370]
Hello!

Via https://github.com/babel/babel/releases?q=7.18.0&expanded=true, `@babel/runtime` v7.18.0+ inlines `regeneratorRuntime` as a helper that does not pollute the global scope. This means that `regeneratorRuntime` references in this project (https://github.com/indexeddbshim/IndexedDBShim/blob/main/dist/indexeddbshim-noninvasive.js#L3813 is a good example) will throw an `Uncaught ReferenceError: regeneratorRuntime is not defined` in environments using newer versions of `@babel/runtime`.

Would it be possible to update the various usage of @babel/runtime to v7.18.0+ in this project?

**Comment by brettz9** [comment]
Released v10.1.0 which should fix the issue. Closing but feel free to comment further as needed. Thanks for the report!

**Comment by colbymelvin** [comment]
Thank you so much @brettz9 , just confirmed on my side that v10.1.0 fixes our issue and unblocks our adoption of `@babel/runtime` > v7.18.0!
