### ISSUE TITLE
Supporting cursor direction / ORDER BY DESC

### ISSUE THREAD

**Issue by Cordemans** [indexeddbshim/IndexedDBShim#38]
Hi there,

First of all, thanks for this amazing project.
And tell me if you need more information or clarification about this issue (first time at github).

One thing I have noticed is that the cursor direction is not supported. If I set "prev" as the direction, the ORDER BY is not set to DESC.

For example:
[...] index.openCursor(null,'prev') [...]

A "simple" solution would be to check the me.direction value.

I have changed this (line 198):

sql.push("ORDER BY ",me.__keyColumnName);

To:

var direction = (me.direction == 'prev' || me.direction == 'prevunique' ? 'DESC' : 'ASC');
sql.push("ORDER BY " + me.__keyColumnName + '  ' + direction);

And that seems to do the trick.

Here are the possible values for direction:
http://www.w3.org/TR/IndexedDB/#cursor-concept

**Comment by JamesMessinger** [comment]
This should be fixed now (as of version 1.0.5).  Please give it a try and let us know if you find any problems.  Thanks!
