### ISSUE TITLE
keyPath: "idIndexedDB", autoIncrement:true , idIndexedDB is undefined?

### ISSUE THREAD

**Issue by ctoph3r** [indexeddbshim/IndexedDBShim#40]
the structure of my objectStore is as following:
var objectStore = thisDb.createObjectStore("test0001", { keyPath: "idIndexedDB", autoIncrement:true });

objectStore.createIndex("idIndexedDB", "idIndexedDB", { unique: true });

objectStore.createIndex("id", "id", { unique: true });

objectStore.createIndex("name", "name", { unique: false });

i have input two records:
1) id: 20001, name: test1
2) id: 20002, name: test2

my function display() is as following:
function display(){

var transaction = db.transaction("test0001","readwrite");

var objectStore = transaction.objectStore("test0001");

var request = objectStore.openCursor();

request.onsuccess = function(event) {

var cursor = event.target.result;

if(cursor){

var value = cursor.value;

alert('id--'+value.id+'--name--'+value.name+'--idIndexedDB--'+value.idIndexedDB)

cursor.continue();

}

}

}

when i call the function display() in firefox, i get two alert, showing me idIndexedDB--1 and idIndexedDB--2, but in safari, the idIndexedDB is undefined?

Here is my full code :
https://gist.github.com/4563826

**Comment by alanmshelly** [comment]
I'm seeing the same problem on both Safari and the Android browser.
When I look at the request result I see a key value returned but it's not inserted properly in the websql db.

**Comment by DickvdBrink** [comment]
Thanks for the issue, it is the same as #108.
Hope to fix it in the future, thanks!

**Comment by JamesMessinger** [comment]
This should be fixed now (as of version 1.0.5).  Please give it a try and let us know if you find any problems.  Thanks!
