### ISSUE TITLE
transaction.oncomplete called once per created store / index, instead of once after all created

### ISSUE THREAD

**Issue by mvayngrib** [indexeddbshim/IndexedDBShim#44]
When upgrading the db and creating N object stores and M indexes, in the onupgradeneeded callback, e.target.transaction.oncomplete is called N + M times, instead of once at the end of the transaction.

**Comment by JamesMessinger** [comment]
This issue has been fixed in the latest version.   Please give it a try and let us know if there are any problems.  Thanks!
