### ISSUE TITLE
IDBDatabase.createObjectStore does not fire oncomplete

### ISSUE THREAD

**Issue by micahnz** [indexeddbshim/IndexedDBShim#53]
oncomplete is not fired on the transaction after the store is created.

added result.transaction.oncomplete(); as a hack for the time being after success(result)

**Comment by micahnz** [comment]
Actually a better alternative was to just add me.oncomplete where there is a comment to implement oncomplete

....

// TODO - Call transaction oncomplete 
me.oncomplete()

.....

This gave me the functionality I needed to integrate with my existing code.

**Comment by JamesMessinger** [comment]
This issue has been fixed in the latest version.   Please give it a try and let us know if there are any problems.  Thanks!
