### ISSUE TITLE
uniqueness not respected for indexes

### ISSUE THREAD

**Issue by mvayngrib** [indexeddbshim/IndexedDBShim#56]
I have an index with settings {multiEntry: false, unique: true}  on the __uri column of one of my object stores. 

When I add an object to the store that has the same __uri property value as an object already in the store, I don't get an error and end up with two (and eventually more) entries in the store with the same __uri value.

**Comment by brettz9** [comment]
This is a confirmed issue (next item on my to-do list).

**Comment by brettz9** [comment]
This should now be fixed in `master` along with other fixes and updates. Thanks for the report!

**Comment by mvayngrib** [comment]
@brettz9 thanks for fixing :)
