### ISSUE TITLE
Blob objects aren't saved well

### ISSUE THREAD

**Issue by Toneti777** [indexeddbshim/IndexedDBShim#59]
I try to save a blob object (image convert to blob) into a webSQL database using the IndexedDB Polyfill on Chrome...

I think that the blob object is been stored like a normal object (JSON String)...this is the log I receive..

SQL for adding INSERT INTO  'imgBGEjemplaresComprados' ( key, value ) VALUES ( ?, ?) 
Array[2]
0: "2-http://programaquiosco.renr.es:8080/datosQuiosco/ejemplares/www.lanueva....."
1: "{"type":"image/jpg","size":89276}"
length: 2
**proto**: Array[0]

The second element should be the blob but the size of table is small.

When I retreive the value, I can't convert it to URL and have a type error..

There are any solution??

Thanks in advance, and sorry about my English.

**Comment by Toneti777** [comment]
Any comments??

**Comment by doonmcgill** [comment]
To verify this, use an sqlite browser (I use the sqlite addon in firefox) to look inside the websql database (the db file - in Ubuntu - is at ~/.config/google-chrome/Default/databases/file_0 and in my system is simply called "1"). You can see what is actually stored...

**Comment by SergiDiaz** [comment]
I've just found this bug in my code, anybody has a solution? Facebook indexedDB polyfill doesn't work, neither.

**Comment by JamesMessinger** [comment]
Can you please try this again with the latest version of IndexedDBShim?  We've [fixed a ton of bugs](https://github.com/axemclion/IndexedDBShim/issues/178#issuecomment-93052746) lately, including many involving how data is serialized and deserialized.
