### ISSUE TITLE
Adding ErrorCodes

### ISSUE THREAD

**Issue by kristofdegrave** [indexeddbshim/IndexedDBShim#6]
When something goes wrong, I get event data back with a message and everything, but an errorcode would be usefull too. This way I can easily ignore errors in some cases.

**Comment by JamesMessinger** [comment]
We've done a lot of work lately to make sure the IndexedDBShim behaves the same as native IndexedDB implementations - including our error-handling logic.   All of our errors now have a `name` property that matches native implementations.  You can use this property to handle different errors in different ways.
