### ISSUE TITLE
Error when inserting data with a key parameter and objectstore with inline keys

### ISSUE THREAD

**Issue by kristofdegrave** [indexeddbshim/IndexedDBShim#7]
I got the follow exception while inserting data with a key parameter and objectstore with inline keys. I think this error/exception isn't handled nice because it blocks further working while I use error handling.

Uncaught exception: SyntaxError: Function constructor: failed to compile functionError thrown at line 34, column 3 in throwDOMException(name, message, error) in http://localhost:50046/Scripts/indexeddb.shim.js:
    var e = new DOMException.constructor(0, message);
called from line 550, column 6 in <anonymous function: IDBObjectStore.prototype.__deriveKey>(props) in http://localhost:50046/Scripts/indexeddb.shim.js:
    idbModules.util.throwDOMException(0, "Data Error - The object store uses in-line keys and the key parameter was provided", props);
called from line 515, column 7 in <anonymous function: IDBObjectStore.prototype.__getStoreProps>(tx, data) in http://localhost:50046/Scripts/indexeddb.shim.js:
    callback(me.__storeProps);
Linq2IndexedDB.js:909
Insert Started, Object , 1, 1
indexeddb.shim.js:34
0, Data Error - The object store uses in-line keys and the key parameter was provided, Object 
indexeddb.shim.js:848
An error in transaction,

**Comment by JamesMessinger** [comment]
Can you please try this again with the latest version of IndexedDBShim?   We've made a bunch of changes recently to make the shim behave the same as native IndexedDB implementations, so this behavior should be better now.
