### ISSUE TITLE
Jquery-IndexedDb example not loading data on stock Android browser

### ISSUE THREAD

**Issue by mcfarljw** [indexeddbshim/IndexedDBShim#76]
I'm going to narrow down on this issue a bit. I'm running the following example on my mobile devices (2.3.6, 4.1.2, 4.2.2) using the **stock Android browser**:

http://nparashuram.com/jquery-indexeddb/example/

The website structure is loading, but the data isn't loading. I'm also not seeing any errors as to why this might be happening. Can anyone else confirm that the data isn't loading when using the stock Android browser on at least the version I mentioned?

**Comment by mcfarljw** [comment]
Here is an image showing the url and outcome:

![2013-09-03 16 11 56](https://f.cloud.github.com/assets/4167341/1071212/af99cc4e-1470-11e3-9626-3e2a265e08ca.png)

**Comment by ghost** [comment]
I have the same issue when using `objectStore.index(...).openCursor(IDBKeyRange.only(...))`, `e.target.result` is simply `undefined`. Not sure what causes this. Have you found a solution yet?

**Comment by mcfarljw** [comment]
I haven't had too much time to mess around with it. What I did is just tell my customers to use mobile Chrome of Firefox for the time being.

**Comment by brettz9** [comment]
@mcfarljw , @ghost , are these problems still occurring?

**Comment by mcfarljw** [comment]
I'm going to say no. I haven't tried it in awhile, but Android has come a long way since the initial issue occurred.

**Comment by brettz9** [comment]
All right, thanks for the report back. I'll close for now, but feel free to reopen or add a new issue. Thanks!
