### ISSUE TITLE
Many __sysdb__ objects being created in Web SQL

### ISSUE THREAD

**Issue by blackmambahk** [indexeddbshim/IndexedDBShim#83]
Hi there,
We are currently using the minified shim in a project.

I am developing on Chrome 29 which I think means in theory the shim should do nothing, however when I check the Resources Tab in Chrome Tools I am getting a lot of Web SQL databases created  each with an empty table "**sysdb**", as I write this there are 9 of them.

Nothing else is there and all our own tables are correctly under IndexedDB not WebSql.

Is there a way to stop this?

**Comment by hx** [comment]
+1

**Comment by axemclion** [comment]
Can you send a pull request for this. If IndexedDB is detected, we can stop the shim altogether.

**Comment by JamesMessinger** [comment]
This is fixed now (as of version 1.0.7).  Thanks for reporting it!

**Comment by JamesMessinger** [comment]
This also fixes https://github.com/axemclion/IndexedDBShim/issues/155
