### ISSUE TITLE
Not working in my Chrome for iOS 7.0

### ISSUE THREAD

**Issue by LeoM-Oto** [indexeddbshim/IndexedDBShim#88]
Hi,

I have a working app using IndexedDB but it only works in my Desktop Chrome. So, I came here for this polyfill... The problem is that I add this line: <script type="text/javascript" src="IndexedDBShim.min.js"> </script>, but it does not work in my Chrome for iOS 7.0... 

I am getting this error: "Database error: undefined". (it happens when I try to open the DB)

Am I missing something? I thought it just needed to add the js file in the way I mentioned above. 

I have run the test from the website but it stops at the 19th one. The other 18 apparently passed.

**Comment by JamesMessinger** [comment]
Can you please try this again with the latest version?  We've fixed a bunch of bugs and have [verified that it's working](https://github.com/axemclion/IndexedDBShim/issues/178#issuecomment-93052746) on several different browsers and devices.
