### ISSUE TITLE
update cart data

### ISSUE THREAD

**Issue by neerajjoshi** [indexeddbshim/IndexedDBShim#95]
Hello Sir,

I am using the example from the below link 

http://nparashuram.com/jquery-indexeddb/example/  for indexed db . It is working fine and a grate plugin

I need help in cart section add to cart and delete cart is working fine but I want to change the value of data in cart like change name from "Music players" to dummy using the auto increment id of cart table but it is not working it add data instead of updating it however delete cart is working fine. Can you please give the link or code sample regarding  how to update the data on the basis of its auto incremented key 

Thanks

**Comment by JamesMessinger** [comment]
The `put()` and `add()` methods have been fixed in the latest version.   Please give it a try and let us know if there are any problems.  Thanks!
